import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1781249207229 implements MigrationInterface {
    name = 'AutoMigration1781249207229'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP CONSTRAINT "FK_fd42ae3a8b32272954162e4eb5a"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP CONSTRAINT "FK_4af0f9cf805eb53c5fc45a0909f"`);
        await queryRunner.query(`CREATE TYPE "public"."youth_service_requests_status_enum" AS ENUM('open', 'in_progress', 'closed')`);
        await queryRunner.query(`CREATE TABLE "youth_service_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "student_id" uuid, "category" character varying(100) NOT NULL, "title" character varying(160) NOT NULL, "description" text NOT NULL, "status" "public"."youth_service_requests_status_enum" NOT NULL DEFAULT 'open', "resolved_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6f3026a8b06878d7edb388d3b0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_youth_service_requests_status" ON "youth_service_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_youth_service_requests_student" ON "youth_service_requests" ("student_id") `);
        await queryRunner.query(`CREATE TYPE "public"."youth_meal_menus_mealtype_enum" AS ENUM('breakfast', 'lunch', 'dinner', 'snack')`);
        await queryRunner.query(`CREATE TABLE "youth_meal_menus" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "menu_date" date NOT NULL, "mealType" "public"."youth_meal_menus_mealtype_enum" NOT NULL, "title" character varying(160) NOT NULL, "description" text, "calories" integer, "allergens" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_0d0e2149770580cfd4411d16760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_youth_meal_menus_date" ON "youth_meal_menus" ("menu_date") `);
        await queryRunner.query(`CREATE TYPE "public"."approval_requests_priority_enum" AS ENUM('low', 'normal', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."approval_requests_status_enum" AS ENUM('pending', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "approval_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "entity_type" character varying(100) NOT NULL, "entity_id" uuid NOT NULL, "requested_by_id" uuid, "approver_id" uuid, "title" character varying(220) NOT NULL, "description" text, "priority" "public"."approval_requests_priority_enum" NOT NULL DEFAULT 'normal', "status" "public"."approval_requests_status_enum" NOT NULL DEFAULT 'pending', "decision_comment" text, "decided_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_484806bb8ff331b851fc75973c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78ff8804358cc7469b3382daa4" ON "approval_requests" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."transport_vehicles_status_enum" AS ENUM('active', 'maintenance', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "transport_vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "plate_number" character varying(40) NOT NULL, "model" character varying(120) NOT NULL, "capacity" integer NOT NULL, "driver_id" uuid, "status" "public"."transport_vehicles_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_0976841dd3c11f363a16faf1a44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b12bd8639bc48e942d7a84ef46" ON "transport_vehicles" ("plate_number") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."transport_trips_status_enum" AS ENUM('planned', 'started', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "transport_trips" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "route_id" uuid NOT NULL, "vehicle_id" uuid, "driver_id" uuid, "trip_date" date NOT NULL, "status" "public"."transport_trips_status_enum" NOT NULL DEFAULT 'planned', "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_44f8fa31e37c9f6003efb645e2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5d80dd31bc2743cb59bb98bfcc" ON "transport_trips" ("route_id", "trip_date") `);
        await queryRunner.query(`CREATE TABLE "student_transport_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "student_id" uuid NOT NULL, "route_id" uuid NOT NULL, "pickup_stop_id" uuid, "dropoff_stop_id" uuid, "monthly_fee" numeric(12,2) NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_8277170362b24b6d0c212dc55da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e2f0da861a0a608b83fe282e19" ON "student_transport_assignments" ("student_id") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."transport_routes_status_enum" AS ENUM('active', 'paused', 'archived')`);
        await queryRunner.query(`CREATE TABLE "transport_routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "name" character varying(160) NOT NULL, "vehicle_id" uuid, "driver_id" uuid, "start_time" character varying(10), "end_time" character varying(10), "status" "public"."transport_routes_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_e4eb047cf1dd4133a5fe314ddf7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_062338936c0a6b7dddc95b6365" ON "transport_routes" ("name") `);
        await queryRunner.query(`CREATE TABLE "transport_route_stops" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "route_id" uuid NOT NULL, "name" character varying(180) NOT NULL, "order_index" integer NOT NULL DEFAULT '0', "arrival_time" character varying(10), "latitude" numeric(10,7), "longitude" numeric(10,7), CONSTRAINT "PK_d90d9718ee8d146499a21c4ee44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e93e2e76566f3080ee3518a0aa" ON "transport_route_stops" ("route_id", "order_index") `);
        await queryRunner.query(`CREATE TABLE "timetable_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "name" character varying(100) NOT NULL, "academic_year_id" uuid, "class_id" uuid, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_13f1c9c16b2ba16edf0a42ab261" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_timetable_templates_class" ON "timetable_templates" ("class_id") `);
        await queryRunner.query(`CREATE TABLE "timetable_substitutions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "slot_id" uuid NOT NULL, "original_teacher_id" uuid, "substitute_teacher_id" uuid NOT NULL, "date" date NOT NULL, "reason" character varying(160), "status" character varying(40) NOT NULL, CONSTRAINT "PK_759068385dd47ced134e4c843a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_timetable_substitutions_date" ON "timetable_substitutions" ("date") `);
        await queryRunner.query(`CREATE INDEX "idx_timetable_substitutions_slot" ON "timetable_substitutions" ("slot_id") `);
        await queryRunner.query(`CREATE TABLE "timetable_slots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "template_id" uuid NOT NULL, "class_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "teacher_id" uuid NOT NULL, "room_id" uuid, "weekday" integer NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "notes" text, CONSTRAINT "PK_b2253a56b9d36d00f84aff7efcc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_timetable_slots_teacher" ON "timetable_slots" ("teacher_id") `);
        await queryRunner.query(`CREATE INDEX "idx_timetable_slots_class" ON "timetable_slots" ("class_id") `);
        await queryRunner.query(`CREATE INDEX "idx_timetable_slots_template" ON "timetable_slots" ("template_id") `);
        await queryRunner.query(`CREATE TABLE "timetable_conflicts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "slot_id" uuid NOT NULL, "conflict_type" character varying(60) NOT NULL, "message" text NOT NULL, "resolved" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_258330c485fb51db37559874100" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_timetable_conflicts_slot" ON "timetable_conflicts" ("slot_id") `);
        await queryRunner.query(`CREATE TABLE "vendors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "name" character varying(140) NOT NULL, "phone" character varying(30), "email" character varying(120), "tax_number" character varying(50), "address" text, "status" character varying(40) NOT NULL, CONSTRAINT "PK_9c956c9797edfae5c6ddacc4e6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_vendors_status" ON "vendors" ("status") `);
        await queryRunner.query(`CREATE TABLE "purchase_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "request_no" character varying(60) NOT NULL, "requested_by_id" uuid, "department_id" uuid, "purpose" text NOT NULL, "estimated_amount" numeric(14,2) NOT NULL DEFAULT '0', "status" character varying(40) NOT NULL, CONSTRAINT "PK_f3c5a8ff7bd4338f4c860925c8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_purchase_requests_no" ON "purchase_requests" ("request_no") `);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "order_no" character varying(60) NOT NULL, "vendor_id" uuid NOT NULL, "request_id" uuid, "order_date" date NOT NULL, "total_amount" numeric(14,2) NOT NULL DEFAULT '0', "status" character varying(40) NOT NULL, CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_purchase_orders_request" ON "purchase_orders" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "idx_purchase_orders_vendor" ON "purchase_orders" ("vendor_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_purchase_orders_no" ON "purchase_orders" ("order_no") `);
        await queryRunner.query(`CREATE TABLE "goods_receipts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "receipt_no" character varying(60) NOT NULL, "purchase_order_id" uuid NOT NULL, "received_at" TIMESTAMP WITH TIME ZONE NOT NULL, "received_by_id" uuid, "notes" text, "status" character varying(40) NOT NULL, CONSTRAINT "PK_f8cac411be0211f923e1be8534f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_goods_receipts_po" ON "goods_receipts" ("purchase_order_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_goods_receipts_no" ON "goods_receipts" ("receipt_no") `);
        await queryRunner.query(`CREATE TABLE "lms_journal_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "lesson_id" uuid NOT NULL, "student_id" uuid NOT NULL, "grade" smallint, "homework_done" boolean NOT NULL DEFAULT false, "comment" text, CONSTRAINT "PK_49c32683e8482f44ee5b1f2f1c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_lms_journal_student" ON "lms_journal_entries" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "idx_lms_journal_lesson" ON "lms_journal_entries" ("lesson_id") `);
        await queryRunner.query(`CREATE TYPE "public"."lms_lesson_schedules_status_enum" AS ENUM('planned', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "lms_lesson_schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "class_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "teacher_id" uuid, "room_id" uuid, "lesson_period_id" uuid, "lesson_date" date NOT NULL, "status" "public"."lms_lesson_schedules_status_enum" NOT NULL DEFAULT 'planned', "topic" text, CONSTRAINT "PK_e44784e7f2c3dd28de5070d9a45" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_lms_lessons_class" ON "lms_lesson_schedules" ("class_id") `);
        await queryRunner.query(`CREATE INDEX "idx_lms_lessons_date" ON "lms_lesson_schedules" ("lesson_date") `);
        await queryRunner.query(`CREATE TABLE "lms_exam_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "exam_id" uuid NOT NULL, "student_id" uuid NOT NULL, "score" numeric(8,2) NOT NULL, "comment" text, CONSTRAINT "PK_c0d290397d7d0df33b6753629f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_lms_exam_results_exam_student_active" ON "lms_exam_results" ("exam_id", "student_id") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."lms_exams_status_enum" AS ENUM('draft', 'scheduled', 'finished')`);
        await queryRunner.query(`CREATE TABLE "lms_exams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "title" character varying(120) NOT NULL, "class_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "exam_date" date NOT NULL, "max_score" numeric(8,2) NOT NULL DEFAULT '100', "status" "public"."lms_exams_status_enum" NOT NULL DEFAULT 'draft', CONSTRAINT "PK_437181c97d60083d206037df11e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_lms_exams_date" ON "lms_exams" ("exam_date") `);
        await queryRunner.query(`CREATE INDEX "idx_lms_exams_class" ON "lms_exams" ("class_id") `);
        await queryRunner.query(`CREATE TABLE "library_reservations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "book_id" uuid NOT NULL, "student_id" uuid, "staff_member_id" uuid, "reserved_at" TIMESTAMP WITH TIME ZONE NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE, "status" character varying(40) NOT NULL, CONSTRAINT "PK_747dacf4a6fe7bdcf033f2e722a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_library_reservations_student" ON "library_reservations" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "idx_library_reservations_book" ON "library_reservations" ("book_id") `);
        await queryRunner.query(`CREATE TABLE "library_loans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "copy_id" uuid NOT NULL, "student_id" uuid, "staff_member_id" uuid, "loaned_at" TIMESTAMP WITH TIME ZONE NOT NULL, "due_date" date NOT NULL, "returned_at" TIMESTAMP WITH TIME ZONE, "fine_amount" numeric(14,2) NOT NULL DEFAULT '0', "status" character varying(40) NOT NULL, CONSTRAINT "PK_e6353ef151c8aee64dbc74d1ecb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_library_loans_status" ON "library_loans" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_library_loans_student" ON "library_loans" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "idx_library_loans_copy" ON "library_loans" ("copy_id") `);
        await queryRunner.query(`CREATE TABLE "library_books" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "title" character varying(180) NOT NULL, "author" character varying(140), "isbn" character varying(40), "category" character varying(80), "publisher" character varying(120), "published_year" integer, "description" text, CONSTRAINT "PK_6054209bc9f4326318a33fcda68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_library_books_isbn" ON "library_books" ("isbn") `);
        await queryRunner.query(`CREATE TABLE "library_book_copies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "book_id" uuid NOT NULL, "barcode" character varying(80) NOT NULL, "status" character varying(40) NOT NULL, "location" character varying(120), CONSTRAINT "PK_0284f4497949a33732ec2caa5f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_library_book_copies_book" ON "library_book_copies" ("book_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_library_book_copies_barcode" ON "library_book_copies" ("barcode") `);
        await queryRunner.query(`CREATE TYPE "public"."kpi_results_target_type_enum" AS ENUM('staff', 'student', 'class', 'school')`);
        await queryRunner.query(`CREATE TYPE "public"."kpi_results_period_type_enum" AS ENUM('daily', 'weekly', 'monthly', 'quarterly')`);
        await queryRunner.query(`CREATE TABLE "kpi_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "metric_id" uuid NOT NULL, "target_type" "public"."kpi_results_target_type_enum" NOT NULL, "target_id" uuid, "period_type" "public"."kpi_results_period_type_enum" NOT NULL, "period_start" date NOT NULL, "period_end" date NOT NULL, "value" numeric(10,2) NOT NULL, "target" numeric(10,2), "score" numeric(7,2), "comment" text, CONSTRAINT "PK_57be4620ae2c0aa403040be0c4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ccf4fdd6c45f2acc4f83167bbe" ON "kpi_results" ("target_type", "target_id", "period_start", "period_end") `);
        await queryRunner.query(`CREATE TYPE "public"."kpi_metrics_target_type_enum" AS ENUM('staff', 'student', 'class', 'school')`);
        await queryRunner.query(`CREATE TABLE "kpi_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "code" character varying(80) NOT NULL, "title" character varying(160) NOT NULL, "description" text, "target_type" "public"."kpi_metrics_target_type_enum" NOT NULL, "weight" numeric(6,2) NOT NULL DEFAULT '1', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b3c9fffe578f0506ce731f0085b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_84c62b61a81645069337fc0cee" ON "kpi_metrics" ("code") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "inventory_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "name" character varying(80) NOT NULL, "code" character varying(40) NOT NULL, "description" text, CONSTRAINT "PK_9903ce18e20acdba3c32c997dc7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_inventory_categories_code_active" ON "inventory_categories" ("code") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_items_status_enum" AS ENUM('active', 'in_repair', 'written_off')`);
        await queryRunner.query(`CREATE TABLE "inventory_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "asset_code" character varying(60) NOT NULL, "name" character varying(120) NOT NULL, "category_id" uuid, "room_id" uuid, "purchase_date" date, "purchase_price" numeric(14,2) NOT NULL DEFAULT '0', "status" "public"."inventory_items_status_enum" NOT NULL DEFAULT 'active', "note" text, CONSTRAINT "PK_cf2f451407242e132547ac19169" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_inventory_items_category" ON "inventory_items" ("category_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_inventory_items_asset_code_active" ON "inventory_items" ("asset_code") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_transactions_type_enum" AS ENUM('income', 'issue', 'return', 'write_off', 'adjustment')`);
        await queryRunner.query(`CREATE TABLE "inventory_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "item_id" uuid NOT NULL, "type" "public"."inventory_transactions_type_enum" NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "performed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "comment" text, CONSTRAINT "PK_9b7144851f08f9eededde7edd42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_inventory_transactions_type" ON "inventory_transactions" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_inventory_transactions_item" ON "inventory_transactions" ("item_id") `);
        await queryRunner.query(`CREATE TYPE "public"."data_jobs_type_enum" AS ENUM('import', 'export')`);
        await queryRunner.query(`CREATE TYPE "public"."data_jobs_entity_type_enum" AS ENUM('students', 'parents', 'staff', 'payments', 'attendance', 'products', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."data_jobs_status_enum" AS ENUM('queued', 'processing', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "data_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "type" "public"."data_jobs_type_enum" NOT NULL, "entity_type" "public"."data_jobs_entity_type_enum" NOT NULL DEFAULT 'other', "file_url" text, "requested_by_id" uuid, "status" "public"."data_jobs_status_enum" NOT NULL DEFAULT 'queued', "total_rows" integer NOT NULL DEFAULT '0', "success_rows" integer NOT NULL DEFAULT '0', "failed_rows" integer NOT NULL DEFAULT '0', "result_file_url" text, "error_report" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_34b1444e02f27adc701eb81091e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32f9fcda0d5287138ce7e0b242" ON "data_jobs" ("type", "entity_type", "status") `);
        await queryRunner.query(`CREATE TABLE "hr_departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "name" character varying(80) NOT NULL, "code" character varying(40) NOT NULL, "description" text, CONSTRAINT "PK_5974c96610b6047c02cb9f6dea1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_hr_departments_code_active" ON "hr_departments" ("code") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "hr_positions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "title" character varying(80) NOT NULL, "code" character varying(40) NOT NULL, "base_salary" numeric(14,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_8c819fecf1bf5916469218fdfa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_hr_positions_code_active" ON "hr_positions" ("code") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."hr_staff_leaves_status_enum" AS ENUM('requested', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "hr_staff_leaves" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "staff_member_id" uuid NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "reason" character varying(120) NOT NULL, "status" "public"."hr_staff_leaves_status_enum" NOT NULL DEFAULT 'requested', CONSTRAINT "PK_d2d236f53ad7e92d15d6bb3b70f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_hr_staff_leaves_status" ON "hr_staff_leaves" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_hr_staff_leaves_staff" ON "hr_staff_leaves" ("staff_member_id") `);
        await queryRunner.query(`CREATE TYPE "public"."hr_payrolls_status_enum" AS ENUM('draft', 'approved', 'paid')`);
        await queryRunner.query(`CREATE TABLE "hr_payrolls" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "staff_member_id" uuid NOT NULL, "period" character varying(7) NOT NULL, "base_amount" numeric(14,2) NOT NULL, "bonus" numeric(14,2) NOT NULL DEFAULT '0', "deduction" numeric(14,2) NOT NULL DEFAULT '0', "net_amount" numeric(14,2) NOT NULL, "status" "public"."hr_payrolls_status_enum" NOT NULL DEFAULT 'draft', CONSTRAINT "PK_88908a5f26ffde82e6313db93ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_hr_payrolls_period" ON "hr_payrolls" ("period") `);
        await queryRunner.query(`CREATE INDEX "idx_hr_payrolls_staff" ON "hr_payrolls" ("staff_member_id") `);
        await queryRunner.query(`CREATE TYPE "public"."hr_staff_members_status_enum" AS ENUM('active', 'on_leave', 'dismissed')`);
        await queryRunner.query(`CREATE TABLE "hr_staff_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "employee_code" character varying(40) NOT NULL, "user_id" uuid, "first_name" character varying(80) NOT NULL, "last_name" character varying(80) NOT NULL, "phone" character varying(20), "email" character varying(120), "department_id" uuid, "position_id" uuid, "hire_date" date NOT NULL, "status" "public"."hr_staff_members_status_enum" NOT NULL DEFAULT 'active', "salary" numeric(14,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_9cfb5f2e227b9d2fd87b8ca8390" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_hr_staff_position" ON "hr_staff_members" ("position_id") `);
        await queryRunner.query(`CREATE INDEX "idx_hr_staff_department" ON "hr_staff_members" ("department_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_hr_staff_employee_code_active" ON "hr_staff_members" ("employee_code") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."homework_submissions_status_enum" AS ENUM('submitted', 'checked', 'returned')`);
        await queryRunner.query(`CREATE TABLE "homework_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "assignment_id" uuid NOT NULL, "student_id" uuid NOT NULL, "answer" text, "attachment_urls" jsonb NOT NULL DEFAULT '[]', "submitted_at" TIMESTAMP WITH TIME ZONE, "score" numeric(7,2), "teacher_comment" text, "ai_feedback" text, "status" "public"."homework_submissions_status_enum" NOT NULL DEFAULT 'submitted', CONSTRAINT "PK_4c570ffb4ce1a34b63afa9d1b26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5f378c22ae9949683e866f84d5" ON "homework_submissions" ("assignment_id", "student_id") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."homework_assignments_status_enum" AS ENUM('draft', 'published', 'closed')`);
        await queryRunner.query(`CREATE TABLE "homework_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "class_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "teacher_id" uuid, "title" character varying(180) NOT NULL, "description" text NOT NULL, "due_date" TIMESTAMP WITH TIME ZONE NOT NULL, "max_score" numeric(7,2) NOT NULL DEFAULT '100', "status" "public"."homework_assignments_status_enum" NOT NULL DEFAULT 'draft', "attachment_urls" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_6e96c9e0467aa788a4ce9c81ac5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e84c10060aa117e059f5809995" ON "homework_assignments" ("class_id", "subject_id", "due_date") `);
        await queryRunner.query(`CREATE TABLE "student_health_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "student_id" uuid NOT NULL, "blood_type" character varying(10), "allergies" text, "medical_notes" text, "emergency_contact" character varying(160), CONSTRAINT "PK_0cd03de02def006d9237847e5b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_student_health_records_student" ON "student_health_records" ("student_id") `);
        await queryRunner.query(`CREATE TABLE "safety_incidents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "title" character varying(160) NOT NULL, "incident_at" TIMESTAMP WITH TIME ZONE NOT NULL, "location" character varying(160), "severity" character varying(40) NOT NULL, "description" text NOT NULL, "status" character varying(40) NOT NULL, CONSTRAINT "PK_3c342c47c53790c3f55ea67723a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_safety_incidents_status" ON "safety_incidents" ("status") `);
        await queryRunner.query(`CREATE TABLE "nurse_visits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "student_id" uuid NOT NULL, "visited_at" TIMESTAMP WITH TIME ZONE NOT NULL, "complaint" text NOT NULL, "treatment" text, "follow_up_required" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_4d7e36d585676b7e1fdb8dfab84" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_nurse_visits_student" ON "nurse_visits" ("student_id") `);
        await queryRunner.query(`CREATE TABLE "emergency_drills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "name" character varying(120) NOT NULL, "drill_date" date NOT NULL, "drill_type" character varying(60) NOT NULL, "participants_count" integer NOT NULL, "notes" text, CONSTRAINT "PK_ed9516ded68b28f0a65ce77e930" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_emergency_drills_date" ON "emergency_drills" ("drill_date") `);
        await queryRunner.query(`CREATE TABLE "student_coin_wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "student_id" uuid NOT NULL, "balance" integer NOT NULL DEFAULT '0', "totalEarned" integer NOT NULL DEFAULT '0', "totalSpent" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_aa54d7be9d1ae9cfa57aa2b5fba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9841907d348656ebc624404a61" ON "student_coin_wallets" ("student_id") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "student_badges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "student_id" uuid NOT NULL, "badge_id" uuid NOT NULL, "awarded_by" uuid, "awarded_reason" text, CONSTRAINT "PK_89c04a467227c27372fd7d22b95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f4c908202c858d56b93742006c" ON "student_badges" ("student_id", "badge_id") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."student_coin_transactions_type_enum" AS ENUM('earn', 'spend', 'adjust')`);
        await queryRunner.query(`CREATE TABLE "student_coin_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "student_id" uuid NOT NULL, "type" "public"."student_coin_transactions_type_enum" NOT NULL, "amount" integer NOT NULL, "reason" character varying(180) NOT NULL, "source_type" character varying(80), "source_id" uuid, CONSTRAINT "PK_e45750df2d694a1cb2644aafabc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d001d8339dc8935ffa2b78b87f" ON "student_coin_transactions" ("student_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "badges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "title" character varying(120) NOT NULL, "description" text, "icon_url" character varying, "rules" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_8a651318b8de577e8e217676466" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."feedback_tickets_type_enum" AS ENUM('message', 'complaint', 'suggestion', 'survey')`);
        await queryRunner.query(`CREATE TYPE "public"."feedback_tickets_status_enum" AS ENUM('new', 'in_progress', 'resolved', 'closed')`);
        await queryRunner.query(`CREATE TABLE "feedback_tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "type" "public"."feedback_tickets_type_enum" NOT NULL DEFAULT 'message', "status" "public"."feedback_tickets_status_enum" NOT NULL DEFAULT 'new', "sender_id" uuid, "student_id" uuid, "assigned_to" uuid, "subject" character varying(180) NOT NULL, "message" text NOT NULL, "rating" integer, "resolved_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_dd8d6f487c66f44d1f6fa6c859b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b76f624e44395f55b9524da2c4" ON "feedback_tickets" ("status", "type") `);
        await queryRunner.query(`CREATE TABLE "feedback_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "ticket_id" uuid NOT NULL, "author_id" uuid, "message" text NOT NULL, "is_internal" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_b7f0dc5cf0fc2dfc18545807317" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_24c7337617037cce7e02b57ca2" ON "feedback_comments" ("ticket_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."document_sign_requests_status_enum" AS ENUM('pending', 'signed', 'rejected', 'expired')`);
        await queryRunner.query(`CREATE TABLE "document_sign_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "document_id" uuid NOT NULL, "signer_id" uuid NOT NULL, "signer_type" character varying(80) NOT NULL, "sent_at" TIMESTAMP WITH TIME ZONE, "signed_at" TIMESTAMP WITH TIME ZONE, "status" "public"."document_sign_requests_status_enum" NOT NULL DEFAULT 'pending', "reject_reason" text, CONSTRAINT "PK_5a22610faeee5e7fd51f8068300" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_690257f677a0f9c9b00f771e3e" ON "document_sign_requests" ("document_id", "signer_id") `);
        await queryRunner.query(`CREATE TYPE "public"."generated_documents_type_enum" AS ENUM('contract', 'certificate', 'order', 'application', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."generated_documents_status_enum" AS ENUM('draft', 'generated', 'signed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "generated_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "template_id" uuid, "owner_type" character varying(80) NOT NULL, "owner_id" uuid NOT NULL, "type" "public"."generated_documents_type_enum" NOT NULL DEFAULT 'other', "title" character varying(220) NOT NULL, "content" text NOT NULL, "file_url" text, "status" "public"."generated_documents_status_enum" NOT NULL DEFAULT 'draft', "metadata" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_93d5f4d6fdc3c0fcc5a7a3aedc2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f1894231b59b3ae119c7fc6900" ON "generated_documents" ("owner_type", "owner_id") `);
        await queryRunner.query(`CREATE TYPE "public"."document_templates_type_enum" AS ENUM('contract', 'certificate', 'order', 'application', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."document_templates_status_enum" AS ENUM('active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "document_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "code" character varying(80) NOT NULL, "name" character varying(180) NOT NULL, "type" "public"."document_templates_type_enum" NOT NULL DEFAULT 'other', "body" text NOT NULL, "variables" jsonb NOT NULL DEFAULT '[]', "status" "public"."document_templates_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_0372838b7b7cd3571aef80466d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_798c5af51f37886fb2fc250005" ON "document_templates" ("code") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TABLE "crm_lead_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "lead_id" uuid NOT NULL, "academic_year_id" uuid, "exam_score" numeric(6,2), "decision" character varying(40) NOT NULL DEFAULT 'pending', "applied_on" date NOT NULL, CONSTRAINT "PK_a8ab56bf96b9e5a9f05f5f46b15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "counseling_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "student_id" uuid NOT NULL, "counselor_id" uuid NOT NULL, "session_date" TIMESTAMP WITH TIME ZONE NOT NULL, "session_type" character varying(40) NOT NULL, "notes_encrypted" text NOT NULL, "risk_level" character varying(20), "follow_up_date" date, CONSTRAINT "PK_9383a822e7e359b12b1b27dea3f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_counseling_sessions_counselor" ON "counseling_sessions" ("counselor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_counseling_sessions_student" ON "counseling_sessions" ("student_id") `);
        await queryRunner.query(`CREATE TYPE "public"."message_templates_channel_enum" AS ENUM('sms', 'telegram', 'email', 'push')`);
        await queryRunner.query(`CREATE TABLE "message_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "code" character varying(80) NOT NULL, "name" character varying(180) NOT NULL, "channel" "public"."message_templates_channel_enum" NOT NULL, "subject" character varying(220), "body" text NOT NULL, "variables" jsonb NOT NULL DEFAULT '[]', "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_9ac2bd9635be662d183f314947d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d83d903fd1bbbe7d3573bc5789" ON "message_templates" ("code") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."message_deliveries_channel_enum" AS ENUM('sms', 'telegram', 'email', 'push')`);
        await queryRunner.query(`CREATE TYPE "public"."message_deliveries_status_enum" AS ENUM('queued', 'sent', 'failed', 'delivered')`);
        await queryRunner.query(`CREATE TABLE "message_deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "campaign_id" uuid, "channel" "public"."message_deliveries_channel_enum" NOT NULL, "recipient_type" character varying(80) NOT NULL, "recipient_id" uuid, "destination" character varying(180) NOT NULL, "subject" character varying(220), "body" text NOT NULL, "status" "public"."message_deliveries_status_enum" NOT NULL DEFAULT 'queued', "provider_message_id" character varying(180), "error_message" text, CONSTRAINT "PK_a582991a821a658d1ffab3d8556" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f0eb653a526fa82a90795a097" ON "message_deliveries" ("recipient_type", "recipient_id") `);
        await queryRunner.query(`CREATE TYPE "public"."communication_campaigns_channel_enum" AS ENUM('sms', 'telegram', 'email', 'push')`);
        await queryRunner.query(`CREATE TYPE "public"."communication_campaigns_status_enum" AS ENUM('draft', 'scheduled', 'running', 'sent', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "communication_campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "name" character varying(180) NOT NULL, "channel" "public"."communication_campaigns_channel_enum" NOT NULL, "template_id" uuid, "subject" character varying(220), "body" text NOT NULL, "target_filter" jsonb NOT NULL DEFAULT '{}', "scheduled_at" TIMESTAMP WITH TIME ZONE, "status" "public"."communication_campaigns_status_enum" NOT NULL DEFAULT 'draft', CONSTRAINT "PK_771b31a5a365e59cf1243e4ee29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d5247cd3dff1d2fa876cae00cf" ON "communication_campaigns" ("channel", "status") `);
        await queryRunner.query(`CREATE TABLE "fixed_assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "asset_code" character varying(80) NOT NULL, "name" character varying(160) NOT NULL, "category" character varying(80), "purchase_date" date, "purchase_cost" numeric(14,2) NOT NULL DEFAULT '0', "current_value" numeric(14,2) NOT NULL DEFAULT '0', "location" character varying(120), "responsible_staff_id" uuid, "status" character varying(40) NOT NULL, CONSTRAINT "PK_901984c25ddf1dcf11f1c7a70d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_fixed_assets_code" ON "fixed_assets" ("asset_code") `);
        await queryRunner.query(`CREATE TABLE "asset_maintenance_tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "asset_id" uuid NOT NULL, "title" character varying(160) NOT NULL, "description" text, "priority" character varying(40) NOT NULL, "status" character varying(40) NOT NULL, "assigned_to_id" uuid, "due_date" date, CONSTRAINT "PK_d248ec1cb9f51aa0c04d177564e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_asset_maintenance_tickets_status" ON "asset_maintenance_tickets" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_asset_maintenance_tickets_asset" ON "asset_maintenance_tickets" ("asset_id") `);
        await queryRunner.query(`CREATE TABLE "asset_depreciations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "asset_id" uuid NOT NULL, "period" character varying(7) NOT NULL, "amount" numeric(14,2) NOT NULL DEFAULT '0', "book_value" numeric(14,2) NOT NULL DEFAULT '0', "notes" text, CONSTRAINT "PK_883381751d81a7a81933910d46a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_asset_depreciations_asset" ON "asset_depreciations" ("asset_id") `);
        await queryRunner.query(`CREATE TABLE "scholarships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "student_id" uuid NOT NULL, "name" character varying(120) NOT NULL, "discount_percent" numeric(14,2) DEFAULT '0', "fixed_amount" numeric(14,2) DEFAULT '0', "start_date" date NOT NULL, "end_date" date, "status" character varying(40) NOT NULL, CONSTRAINT "PK_2a0dde777a7801b91882e4e69e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_scholarships_student" ON "scholarships" ("student_id") `);
        await queryRunner.query(`CREATE TABLE "refunds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "payment_id" uuid, "student_id" uuid, "amount" numeric(14,2) NOT NULL DEFAULT '0', "reason" text NOT NULL, "status" character varying(40) NOT NULL, "processed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_5106efb01eeda7e49a78b869738" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_refunds_student" ON "refunds" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "idx_refunds_payment" ON "refunds" ("payment_id") `);
        await queryRunner.query(`CREATE TABLE "finance_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "invoice_no" character varying(60) NOT NULL, "student_id" uuid, "contract_id" uuid, "issue_date" date NOT NULL, "due_date" date, "amount" numeric(14,2) NOT NULL DEFAULT '0', "paid_amount" numeric(14,2) NOT NULL DEFAULT '0', "status" character varying(40) NOT NULL, CONSTRAINT "PK_ad2f669c00cf30b014b4d23c601" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_finance_invoices_contract" ON "finance_invoices" ("contract_id") `);
        await queryRunner.query(`CREATE INDEX "idx_finance_invoices_student" ON "finance_invoices" ("student_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_finance_invoices_no" ON "finance_invoices" ("invoice_no") `);
        await queryRunner.query(`CREATE TABLE "cashboxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(40) NOT NULL, "currency" character varying(10) NOT NULL, "balance" numeric(14,2) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_a7a5168173c43cb11448fc30d42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_cashboxes_code" ON "cashboxes" ("code") `);
        await queryRunner.query(`CREATE TABLE "bank_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "transaction_no" character varying(100) NOT NULL, "bank_name" character varying(120), "transaction_date" date NOT NULL, "amount" numeric(14,2) NOT NULL DEFAULT '0', "direction" character varying(20) NOT NULL, "matched_payment_id" uuid, "status" character varying(40) NOT NULL, CONSTRAINT "PK_123cc87304eefb2c497b4acdd10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_bank_transactions_payment" ON "bank_transactions" ("matched_payment_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_bank_transactions_no" ON "bank_transactions" ("transaction_no") `);
        await queryRunner.query(`CREATE TABLE "entrance_exams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "application_id" uuid NOT NULL, "subject" character varying(80) NOT NULL, "exam_date" TIMESTAMP WITH TIME ZONE NOT NULL, "score" numeric(14,2) DEFAULT '0', "max_score" numeric(14,2) DEFAULT '0', "result" character varying(40), "comment" text, CONSTRAINT "PK_8193d85c707ea045289f822109a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_entrance_exams_application" ON "entrance_exams" ("application_id") `);
        await queryRunner.query(`CREATE TABLE "admission_stages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "pipeline_id" uuid NOT NULL, "name" character varying(80) NOT NULL, "code" character varying(40) NOT NULL, "order_index" integer NOT NULL, "is_final" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_0b631d6e9fc991a9df899507146" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_admission_stages_pipeline" ON "admission_stages" ("pipeline_id") `);
        await queryRunner.query(`CREATE TABLE "admission_pipelines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "name" character varying(80) NOT NULL, "code" character varying(40) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_cc0b55aa2d7f016fd2c168e1ce5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_admission_pipelines_code" ON "admission_pipelines" ("code") `);
        await queryRunner.query(`CREATE TABLE "admission_decisions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "application_id" uuid NOT NULL, "decision" character varying(40) NOT NULL, "decided_by_id" uuid, "decided_at" TIMESTAMP WITH TIME ZONE NOT NULL, "comment" text, CONSTRAINT "PK_04b73d885e1ea43aa073f6eca9c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_admission_decisions_application" ON "admission_decisions" ("application_id") `);
        await queryRunner.query(`CREATE TABLE "face_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "person_type" character varying(80) NOT NULL, "person_id" uuid NOT NULL, "photo_url" text, "face_template_hash" character varying(220), "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_c16f4eb249363113d4e259faa94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f383b91987443ddf75bb63c085" ON "face_profiles" ("person_type", "person_id") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."access_events_direction_enum" AS ENUM('in', 'out')`);
        await queryRunner.query(`CREATE TYPE "public"."access_events_decision_enum" AS ENUM('allowed', 'denied')`);
        await queryRunner.query(`CREATE TABLE "access_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "device_id" uuid NOT NULL, "person_type" character varying(80), "person_id" uuid, "direction" "public"."access_events_direction_enum" NOT NULL, "decision" "public"."access_events_decision_enum" NOT NULL, "event_time" TIMESTAMP WITH TIME ZONE NOT NULL, "snapshot_url" text, "reason" text, CONSTRAINT "PK_b5edb54463ff60f59a3d40f71e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_083f386344a34cd202ba0d5ab6" ON "access_events" ("person_type", "person_id", "event_time") `);
        await queryRunner.query(`CREATE TYPE "public"."access_devices_type_enum" AS ENUM('face_terminal', 'turnstile', 'camera', 'card_reader')`);
        await queryRunner.query(`CREATE TYPE "public"."access_devices_status_enum" AS ENUM('online', 'offline', 'maintenance')`);
        await queryRunner.query(`CREATE TABLE "access_devices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "serial_number" character varying(120) NOT NULL, "name" character varying(180) NOT NULL, "type" "public"."access_devices_type_enum" NOT NULL, "location" character varying(180), "ip_address" character varying(64), "status" "public"."access_devices_status_enum" NOT NULL DEFAULT 'offline', "last_seen_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7de618364854e31f72073fa8f3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bfe43bf57a16cad303a430ec19" ON "access_devices" ("serial_number") WHERE deleted_at IS NULL`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "lead_id"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "academic_year_id"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "exam_score"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "applied_on"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "decision"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "application_no" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "student_first_name" character varying(80) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "student_last_name" character varying(80) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "birth_date" date`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "parent_full_name" character varying(120) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "parent_phone" character varying(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "grade_level" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "source" character varying(80)`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "stage_id" uuid`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "status" character varying(40) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "notes" text`);
        await queryRunner.query(`ALTER TYPE "public"."appeals_target_role_enum" RENAME TO "appeals_target_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."appeals_target_role_enum" AS ENUM('class_teacher', 'deputy_director', 'director', 'accountant', 'sales_manager', 'psychologist', 'doctor', 'librarian')`);
        await queryRunner.query(`ALTER TABLE "appeals" ALTER COLUMN "target_role" TYPE "public"."appeals_target_role_enum" USING "target_role"::"text"::"public"."appeals_target_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."appeals_target_role_enum_old"`);
        await queryRunner.query(`CREATE INDEX "idx_admission_applications_status" ON "admission_applications" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_admission_applications_stage" ON "admission_applications" ("stage_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_admission_applications_no" ON "admission_applications" ("application_no") `);
        await queryRunner.query(`ALTER TABLE "youth_service_requests" ADD CONSTRAINT "FK_87f10bb46268158da66e82c8131" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lms_journal_entries" ADD CONSTRAINT "FK_750a56d1f8f9a026268c8ff2735" FOREIGN KEY ("lesson_id") REFERENCES "lms_lesson_schedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lms_journal_entries" ADD CONSTRAINT "FK_c40e8a9765b0ad6410372292b87" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lms_lesson_schedules" ADD CONSTRAINT "FK_7c3031d49a66aa3b2de93efbcb2" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lms_lesson_schedules" ADD CONSTRAINT "FK_bbbc7c46527bb7f1fda25602f79" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lms_lesson_schedules" ADD CONSTRAINT "FK_2c1d0ab36a6b0622bea9c6a0481" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lms_lesson_schedules" ADD CONSTRAINT "FK_37ad80fd250ce6c683a7cb2b4ad" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lms_lesson_schedules" ADD CONSTRAINT "FK_b66d7a0bcab0dde2dd98742cf10" FOREIGN KEY ("lesson_period_id") REFERENCES "lesson_periods"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lms_exam_results" ADD CONSTRAINT "FK_8adef3c735ab77ff6bd918008fc" FOREIGN KEY ("exam_id") REFERENCES "lms_exams"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lms_exam_results" ADD CONSTRAINT "FK_47b8bdd812d5885dcabddd6fc7d" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lms_exams" ADD CONSTRAINT "FK_b1c54e8cfc774127d5b897b602c" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lms_exams" ADD CONSTRAINT "FK_88b25a349285247f5ba532654ec" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_934d5a332b6870c7bb95643ab41" FOREIGN KEY ("category_id") REFERENCES "inventory_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_64992810a0f1bf1e8a21ee36919" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_073259120ddd23357a88f7cd113" FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_staff_leaves" ADD CONSTRAINT "FK_21d45257fb8f21fcecacf24a5b1" FOREIGN KEY ("staff_member_id") REFERENCES "hr_staff_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_payrolls" ADD CONSTRAINT "FK_15ee7ad37eceae40e6d4b9c0e18" FOREIGN KEY ("staff_member_id") REFERENCES "hr_staff_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_staff_members" ADD CONSTRAINT "FK_788de56c3b9469452cc77b5d74e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_staff_members" ADD CONSTRAINT "FK_215e2c12cd88e1fe0028c8a71e0" FOREIGN KEY ("department_id") REFERENCES "hr_departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_staff_members" ADD CONSTRAINT "FK_4ca6d8aef126136b9583bc3864d" FOREIGN KEY ("position_id") REFERENCES "hr_positions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crm_lead_applications" ADD CONSTRAINT "FK_1fb88b3af3d6716725e7a12a694" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crm_lead_applications" ADD CONSTRAINT "FK_7a16e3516bee7eb544db728679c" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "crm_lead_applications" DROP CONSTRAINT "FK_7a16e3516bee7eb544db728679c"`);
        await queryRunner.query(`ALTER TABLE "crm_lead_applications" DROP CONSTRAINT "FK_1fb88b3af3d6716725e7a12a694"`);
        await queryRunner.query(`ALTER TABLE "hr_staff_members" DROP CONSTRAINT "FK_4ca6d8aef126136b9583bc3864d"`);
        await queryRunner.query(`ALTER TABLE "hr_staff_members" DROP CONSTRAINT "FK_215e2c12cd88e1fe0028c8a71e0"`);
        await queryRunner.query(`ALTER TABLE "hr_staff_members" DROP CONSTRAINT "FK_788de56c3b9469452cc77b5d74e"`);
        await queryRunner.query(`ALTER TABLE "hr_payrolls" DROP CONSTRAINT "FK_15ee7ad37eceae40e6d4b9c0e18"`);
        await queryRunner.query(`ALTER TABLE "hr_staff_leaves" DROP CONSTRAINT "FK_21d45257fb8f21fcecacf24a5b1"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_073259120ddd23357a88f7cd113"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "FK_64992810a0f1bf1e8a21ee36919"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "FK_934d5a332b6870c7bb95643ab41"`);
        await queryRunner.query(`ALTER TABLE "lms_exams" DROP CONSTRAINT "FK_88b25a349285247f5ba532654ec"`);
        await queryRunner.query(`ALTER TABLE "lms_exams" DROP CONSTRAINT "FK_b1c54e8cfc774127d5b897b602c"`);
        await queryRunner.query(`ALTER TABLE "lms_exam_results" DROP CONSTRAINT "FK_47b8bdd812d5885dcabddd6fc7d"`);
        await queryRunner.query(`ALTER TABLE "lms_exam_results" DROP CONSTRAINT "FK_8adef3c735ab77ff6bd918008fc"`);
        await queryRunner.query(`ALTER TABLE "lms_lesson_schedules" DROP CONSTRAINT "FK_b66d7a0bcab0dde2dd98742cf10"`);
        await queryRunner.query(`ALTER TABLE "lms_lesson_schedules" DROP CONSTRAINT "FK_37ad80fd250ce6c683a7cb2b4ad"`);
        await queryRunner.query(`ALTER TABLE "lms_lesson_schedules" DROP CONSTRAINT "FK_2c1d0ab36a6b0622bea9c6a0481"`);
        await queryRunner.query(`ALTER TABLE "lms_lesson_schedules" DROP CONSTRAINT "FK_bbbc7c46527bb7f1fda25602f79"`);
        await queryRunner.query(`ALTER TABLE "lms_lesson_schedules" DROP CONSTRAINT "FK_7c3031d49a66aa3b2de93efbcb2"`);
        await queryRunner.query(`ALTER TABLE "lms_journal_entries" DROP CONSTRAINT "FK_c40e8a9765b0ad6410372292b87"`);
        await queryRunner.query(`ALTER TABLE "lms_journal_entries" DROP CONSTRAINT "FK_750a56d1f8f9a026268c8ff2735"`);
        await queryRunner.query(`ALTER TABLE "youth_service_requests" DROP CONSTRAINT "FK_87f10bb46268158da66e82c8131"`);
        await queryRunner.query(`DROP INDEX "public"."uq_admission_applications_no"`);
        await queryRunner.query(`DROP INDEX "public"."idx_admission_applications_stage"`);
        await queryRunner.query(`DROP INDEX "public"."idx_admission_applications_status"`);
        await queryRunner.query(`CREATE TYPE "public"."appeals_target_role_enum_old" AS ENUM('class_teacher', 'deputy_director', 'director', 'accountant', 'sales_manager', 'psychologist', 'doctor')`);
        await queryRunner.query(`ALTER TABLE "appeals" ALTER COLUMN "target_role" TYPE "public"."appeals_target_role_enum_old" USING "target_role"::"text"::"public"."appeals_target_role_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."appeals_target_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."appeals_target_role_enum_old" RENAME TO "appeals_target_role_enum"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "stage_id"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "grade_level"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "parent_phone"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "parent_full_name"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "birth_date"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "student_last_name"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "student_first_name"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" DROP COLUMN "application_no"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "decision" character varying(40) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "applied_on" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "exam_score" numeric(6,2)`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "academic_year_id" uuid`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD "lead_id" uuid NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfe43bf57a16cad303a430ec19"`);
        await queryRunner.query(`DROP TABLE "access_devices"`);
        await queryRunner.query(`DROP TYPE "public"."access_devices_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."access_devices_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_083f386344a34cd202ba0d5ab6"`);
        await queryRunner.query(`DROP TABLE "access_events"`);
        await queryRunner.query(`DROP TYPE "public"."access_events_decision_enum"`);
        await queryRunner.query(`DROP TYPE "public"."access_events_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f383b91987443ddf75bb63c085"`);
        await queryRunner.query(`DROP TABLE "face_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."idx_admission_decisions_application"`);
        await queryRunner.query(`DROP TABLE "admission_decisions"`);
        await queryRunner.query(`DROP INDEX "public"."uq_admission_pipelines_code"`);
        await queryRunner.query(`DROP TABLE "admission_pipelines"`);
        await queryRunner.query(`DROP INDEX "public"."idx_admission_stages_pipeline"`);
        await queryRunner.query(`DROP TABLE "admission_stages"`);
        await queryRunner.query(`DROP INDEX "public"."idx_entrance_exams_application"`);
        await queryRunner.query(`DROP TABLE "entrance_exams"`);
        await queryRunner.query(`DROP INDEX "public"."uq_bank_transactions_no"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bank_transactions_payment"`);
        await queryRunner.query(`DROP TABLE "bank_transactions"`);
        await queryRunner.query(`DROP INDEX "public"."uq_cashboxes_code"`);
        await queryRunner.query(`DROP TABLE "cashboxes"`);
        await queryRunner.query(`DROP INDEX "public"."uq_finance_invoices_no"`);
        await queryRunner.query(`DROP INDEX "public"."idx_finance_invoices_student"`);
        await queryRunner.query(`DROP INDEX "public"."idx_finance_invoices_contract"`);
        await queryRunner.query(`DROP TABLE "finance_invoices"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refunds_payment"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refunds_student"`);
        await queryRunner.query(`DROP TABLE "refunds"`);
        await queryRunner.query(`DROP INDEX "public"."idx_scholarships_student"`);
        await queryRunner.query(`DROP TABLE "scholarships"`);
        await queryRunner.query(`DROP INDEX "public"."idx_asset_depreciations_asset"`);
        await queryRunner.query(`DROP TABLE "asset_depreciations"`);
        await queryRunner.query(`DROP INDEX "public"."idx_asset_maintenance_tickets_asset"`);
        await queryRunner.query(`DROP INDEX "public"."idx_asset_maintenance_tickets_status"`);
        await queryRunner.query(`DROP TABLE "asset_maintenance_tickets"`);
        await queryRunner.query(`DROP INDEX "public"."uq_fixed_assets_code"`);
        await queryRunner.query(`DROP TABLE "fixed_assets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5247cd3dff1d2fa876cae00cf"`);
        await queryRunner.query(`DROP TABLE "communication_campaigns"`);
        await queryRunner.query(`DROP TYPE "public"."communication_campaigns_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."communication_campaigns_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f0eb653a526fa82a90795a097"`);
        await queryRunner.query(`DROP TABLE "message_deliveries"`);
        await queryRunner.query(`DROP TYPE "public"."message_deliveries_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."message_deliveries_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d83d903fd1bbbe7d3573bc5789"`);
        await queryRunner.query(`DROP TABLE "message_templates"`);
        await queryRunner.query(`DROP TYPE "public"."message_templates_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_counseling_sessions_student"`);
        await queryRunner.query(`DROP INDEX "public"."idx_counseling_sessions_counselor"`);
        await queryRunner.query(`DROP TABLE "counseling_sessions"`);
        await queryRunner.query(`DROP TABLE "crm_lead_applications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_798c5af51f37886fb2fc250005"`);
        await queryRunner.query(`DROP TABLE "document_templates"`);
        await queryRunner.query(`DROP TYPE "public"."document_templates_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."document_templates_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1894231b59b3ae119c7fc6900"`);
        await queryRunner.query(`DROP TABLE "generated_documents"`);
        await queryRunner.query(`DROP TYPE "public"."generated_documents_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."generated_documents_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_690257f677a0f9c9b00f771e3e"`);
        await queryRunner.query(`DROP TABLE "document_sign_requests"`);
        await queryRunner.query(`DROP TYPE "public"."document_sign_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24c7337617037cce7e02b57ca2"`);
        await queryRunner.query(`DROP TABLE "feedback_comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b76f624e44395f55b9524da2c4"`);
        await queryRunner.query(`DROP TABLE "feedback_tickets"`);
        await queryRunner.query(`DROP TYPE "public"."feedback_tickets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."feedback_tickets_type_enum"`);
        await queryRunner.query(`DROP TABLE "badges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d001d8339dc8935ffa2b78b87f"`);
        await queryRunner.query(`DROP TABLE "student_coin_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."student_coin_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4c908202c858d56b93742006c"`);
        await queryRunner.query(`DROP TABLE "student_badges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9841907d348656ebc624404a61"`);
        await queryRunner.query(`DROP TABLE "student_coin_wallets"`);
        await queryRunner.query(`DROP INDEX "public"."idx_emergency_drills_date"`);
        await queryRunner.query(`DROP TABLE "emergency_drills"`);
        await queryRunner.query(`DROP INDEX "public"."idx_nurse_visits_student"`);
        await queryRunner.query(`DROP TABLE "nurse_visits"`);
        await queryRunner.query(`DROP INDEX "public"."idx_safety_incidents_status"`);
        await queryRunner.query(`DROP TABLE "safety_incidents"`);
        await queryRunner.query(`DROP INDEX "public"."uq_student_health_records_student"`);
        await queryRunner.query(`DROP TABLE "student_health_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e84c10060aa117e059f5809995"`);
        await queryRunner.query(`DROP TABLE "homework_assignments"`);
        await queryRunner.query(`DROP TYPE "public"."homework_assignments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f378c22ae9949683e866f84d5"`);
        await queryRunner.query(`DROP TABLE "homework_submissions"`);
        await queryRunner.query(`DROP TYPE "public"."homework_submissions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_hr_staff_employee_code_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_staff_department"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_staff_position"`);
        await queryRunner.query(`DROP TABLE "hr_staff_members"`);
        await queryRunner.query(`DROP TYPE "public"."hr_staff_members_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_payrolls_staff"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_payrolls_period"`);
        await queryRunner.query(`DROP TABLE "hr_payrolls"`);
        await queryRunner.query(`DROP TYPE "public"."hr_payrolls_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_staff_leaves_staff"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_staff_leaves_status"`);
        await queryRunner.query(`DROP TABLE "hr_staff_leaves"`);
        await queryRunner.query(`DROP TYPE "public"."hr_staff_leaves_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_hr_positions_code_active"`);
        await queryRunner.query(`DROP TABLE "hr_positions"`);
        await queryRunner.query(`DROP INDEX "public"."uq_hr_departments_code_active"`);
        await queryRunner.query(`DROP TABLE "hr_departments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32f9fcda0d5287138ce7e0b242"`);
        await queryRunner.query(`DROP TABLE "data_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."data_jobs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."data_jobs_entity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."data_jobs_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inventory_transactions_item"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inventory_transactions_type"`);
        await queryRunner.query(`DROP TABLE "inventory_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_inventory_items_asset_code_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inventory_items_category"`);
        await queryRunner.query(`DROP TABLE "inventory_items"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_items_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_inventory_categories_code_active"`);
        await queryRunner.query(`DROP TABLE "inventory_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84c62b61a81645069337fc0cee"`);
        await queryRunner.query(`DROP TABLE "kpi_metrics"`);
        await queryRunner.query(`DROP TYPE "public"."kpi_metrics_target_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccf4fdd6c45f2acc4f83167bbe"`);
        await queryRunner.query(`DROP TABLE "kpi_results"`);
        await queryRunner.query(`DROP TYPE "public"."kpi_results_period_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."kpi_results_target_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_library_book_copies_barcode"`);
        await queryRunner.query(`DROP INDEX "public"."idx_library_book_copies_book"`);
        await queryRunner.query(`DROP TABLE "library_book_copies"`);
        await queryRunner.query(`DROP INDEX "public"."idx_library_books_isbn"`);
        await queryRunner.query(`DROP TABLE "library_books"`);
        await queryRunner.query(`DROP INDEX "public"."idx_library_loans_copy"`);
        await queryRunner.query(`DROP INDEX "public"."idx_library_loans_student"`);
        await queryRunner.query(`DROP INDEX "public"."idx_library_loans_status"`);
        await queryRunner.query(`DROP TABLE "library_loans"`);
        await queryRunner.query(`DROP INDEX "public"."idx_library_reservations_book"`);
        await queryRunner.query(`DROP INDEX "public"."idx_library_reservations_student"`);
        await queryRunner.query(`DROP TABLE "library_reservations"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lms_exams_class"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lms_exams_date"`);
        await queryRunner.query(`DROP TABLE "lms_exams"`);
        await queryRunner.query(`DROP TYPE "public"."lms_exams_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_lms_exam_results_exam_student_active"`);
        await queryRunner.query(`DROP TABLE "lms_exam_results"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lms_lessons_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lms_lessons_class"`);
        await queryRunner.query(`DROP TABLE "lms_lesson_schedules"`);
        await queryRunner.query(`DROP TYPE "public"."lms_lesson_schedules_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lms_journal_lesson"`);
        await queryRunner.query(`DROP INDEX "public"."idx_lms_journal_student"`);
        await queryRunner.query(`DROP TABLE "lms_journal_entries"`);
        await queryRunner.query(`DROP INDEX "public"."uq_goods_receipts_no"`);
        await queryRunner.query(`DROP INDEX "public"."idx_goods_receipts_po"`);
        await queryRunner.query(`DROP TABLE "goods_receipts"`);
        await queryRunner.query(`DROP INDEX "public"."uq_purchase_orders_no"`);
        await queryRunner.query(`DROP INDEX "public"."idx_purchase_orders_vendor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_purchase_orders_request"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP INDEX "public"."uq_purchase_requests_no"`);
        await queryRunner.query(`DROP TABLE "purchase_requests"`);
        await queryRunner.query(`DROP INDEX "public"."idx_vendors_status"`);
        await queryRunner.query(`DROP TABLE "vendors"`);
        await queryRunner.query(`DROP INDEX "public"."idx_timetable_conflicts_slot"`);
        await queryRunner.query(`DROP TABLE "timetable_conflicts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_timetable_slots_template"`);
        await queryRunner.query(`DROP INDEX "public"."idx_timetable_slots_class"`);
        await queryRunner.query(`DROP INDEX "public"."idx_timetable_slots_teacher"`);
        await queryRunner.query(`DROP TABLE "timetable_slots"`);
        await queryRunner.query(`DROP INDEX "public"."idx_timetable_substitutions_slot"`);
        await queryRunner.query(`DROP INDEX "public"."idx_timetable_substitutions_date"`);
        await queryRunner.query(`DROP TABLE "timetable_substitutions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_timetable_templates_class"`);
        await queryRunner.query(`DROP TABLE "timetable_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e93e2e76566f3080ee3518a0aa"`);
        await queryRunner.query(`DROP TABLE "transport_route_stops"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_062338936c0a6b7dddc95b6365"`);
        await queryRunner.query(`DROP TABLE "transport_routes"`);
        await queryRunner.query(`DROP TYPE "public"."transport_routes_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2f0da861a0a608b83fe282e19"`);
        await queryRunner.query(`DROP TABLE "student_transport_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d80dd31bc2743cb59bb98bfcc"`);
        await queryRunner.query(`DROP TABLE "transport_trips"`);
        await queryRunner.query(`DROP TYPE "public"."transport_trips_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b12bd8639bc48e942d7a84ef46"`);
        await queryRunner.query(`DROP TABLE "transport_vehicles"`);
        await queryRunner.query(`DROP TYPE "public"."transport_vehicles_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78ff8804358cc7469b3382daa4"`);
        await queryRunner.query(`DROP TABLE "approval_requests"`);
        await queryRunner.query(`DROP TYPE "public"."approval_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."approval_requests_priority_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_youth_meal_menus_date"`);
        await queryRunner.query(`DROP TABLE "youth_meal_menus"`);
        await queryRunner.query(`DROP TYPE "public"."youth_meal_menus_mealtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_youth_service_requests_student"`);
        await queryRunner.query(`DROP INDEX "public"."idx_youth_service_requests_status"`);
        await queryRunner.query(`DROP TABLE "youth_service_requests"`);
        await queryRunner.query(`DROP TYPE "public"."youth_service_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD CONSTRAINT "FK_4af0f9cf805eb53c5fc45a0909f" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admission_applications" ADD CONSTRAINT "FK_fd42ae3a8b32272954162e4eb5a" FOREIGN KEY ("lead_id") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
