export const AppPermission = {
  // Resurs: grade-requests
  GRADE_REQUESTS_READ: 'grade-requests.read',
  GRADE_REQUESTS_CREATE: 'grade-requests.create',
  GRADE_REQUESTS_UPDATE: 'grade-requests.update',
  GRADE_REQUESTS_DELETE: 'grade-requests.delete',
  // Resurs: parent-communications
  PARENT_COMMUNICATIONS_READ: 'parent-communications.read',
  PARENT_COMMUNICATIONS_CREATE: 'parent-communications.create',
  PARENT_COMMUNICATIONS_UPDATE: 'parent-communications.update',
  PARENT_COMMUNICATIONS_DELETE: 'parent-communications.delete',
  // Resurs: notification-templates
  NOTIFICATION_TEMPLATES_READ: 'notification-templates.read',
  NOTIFICATION_TEMPLATES_CREATE: 'notification-templates.create',
  // Resurs: notification-queue
  NOTIFICATION_QUEUE_CREATE: 'notification-queue.create',
  // Resurs: appeals
  APPEALS_CREATE: 'appeals.create',
  APPEALS_UPDATE: 'appeals.update',
  APPEALS_DELETE: 'appeals.delete',
  // Resurs: appeals-public-link
  APPEALS_PUBLIC_LINK_READ: 'appeals-public-link.read',
  APPEALS_PUBLIC_LINK_CREATE: 'appeals-public-link.create',
  // Resurs: integrations
  INTEGRATIONS_CREATE: 'integrations.create',
  INTEGRATIONS_UPDATE: 'integrations.update',
  INTEGRATIONS_DELETE: 'integrations.delete',
  // Resurs: settings-school
  SETTINGS_SCHOOL_READ: 'settings-school.read',
  SETTINGS_SCHOOL_UPDATE: 'settings-school.update',
  // Resurs: settings-rooms
  SETTINGS_ROOMS_READ: 'settings-rooms.read',
  SETTINGS_ROOMS_CREATE: 'settings-rooms.create',
  SETTINGS_ROOMS_UPDATE: 'settings-rooms.update',
  SETTINGS_ROOMS_DELETE: 'settings-rooms.delete',
  // Resurs: roles
  ROLES_CREATE: 'roles.create',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',
  // Resurs: data-jobs
  DATA_JOBS_CREATE: 'data-jobs.create',
  DATA_JOBS_UPDATE: 'data-jobs.update',
  // Resurs: communication-templates
  COMMUNICATION_TEMPLATES_READ: 'communication-templates.read',
  COMMUNICATION_TEMPLATES_CREATE: 'communication-templates.create',
  COMMUNICATION_TEMPLATES_UPDATE: 'communication-templates.update',
  // Resurs: communication-campaigns
  COMMUNICATION_CAMPAIGNS_READ: 'communication-campaigns.read',
  COMMUNICATION_CAMPAIGNS_CREATE: 'communication-campaigns.create',
  COMMUNICATION_CAMPAIGNS_UPDATE: 'communication-campaigns.update',
  // Resurs: communication-deliveries
  COMMUNICATION_DELIVERIES_READ: 'communication-deliveries.read',
  COMMUNICATION_DELIVERIES_CREATE: 'communication-deliveries.create',
  COMMUNICATION_DELIVERIES_UPDATE: 'communication-deliveries.update',
  // Resurs: feedback-tickets
  FEEDBACK_TICKETS_READ: 'feedback-tickets.read',
  FEEDBACK_TICKETS_CREATE: 'feedback-tickets.create',
  FEEDBACK_TICKETS_UPDATE: 'feedback-tickets.update',
  // Resurs: feedback-comments
  FEEDBACK_COMMENTS_READ: 'feedback-comments.read',
  FEEDBACK_COMMENTS_CREATE: 'feedback-comments.create',
  // Resurs: youth-meal-menus
  YOUTH_MEAL_MENUS_READ: 'youth-meal-menus.read',
  YOUTH_MEAL_MENUS_CREATE: 'youth-meal-menus.create',
  YOUTH_MEAL_MENUS_UPDATE: 'youth-meal-menus.update',
  // Resurs: youth-requests
  YOUTH_REQUESTS_READ: 'youth-requests.read',
  YOUTH_REQUESTS_CREATE: 'youth-requests.create',
  YOUTH_REQUESTS_UPDATE: 'youth-requests.update',
  // Resurs: kpi-metrics
  KPI_METRICS_READ: 'kpi-metrics.read',
  KPI_METRICS_CREATE: 'kpi-metrics.create',
  KPI_METRICS_UPDATE: 'kpi-metrics.update',
  // Resurs: kpi-results
  KPI_RESULTS_READ: 'kpi-results.read',
  KPI_RESULTS_CREATE: 'kpi-results.create',
  KPI_RESULTS_UPDATE: 'kpi-results.update',
  // Resurs: workflow-approvals
  WORKFLOW_APPROVALS_READ: 'workflow-approvals.read',
  WORKFLOW_APPROVALS_CREATE: 'workflow-approvals.create',
  WORKFLOW_APPROVALS_UPDATE: 'workflow-approvals.update',
  // Resurs: access-control-devices
  ACCESS_CONTROL_DEVICES_READ: 'access-control-devices.read',
  ACCESS_CONTROL_DEVICES_CREATE: 'access-control-devices.create',
  ACCESS_CONTROL_DEVICES_UPDATE: 'access-control-devices.update',
  // Resurs: access-control-face-profiles
  ACCESS_CONTROL_FACE_PROFILES_READ: 'access-control-face-profiles.read',
  ACCESS_CONTROL_FACE_PROFILES_CREATE: 'access-control-face-profiles.create',
  // Resurs: access-control-events
  ACCESS_CONTROL_EVENTS_READ: 'access-control-events.read',
  ACCESS_CONTROL_EVENTS_CREATE: 'access-control-events.create',
  // Resurs: transactions
  TRANSACTIONS_READ: 'transactions.read',
  TRANSACTIONS_CREATE: 'transactions.create',
  TRANSACTIONS_UPDATE: 'transactions.update',
  TRANSACTIONS_DELETE: 'transactions.delete',
  // Resurs: transaction-payment-types
  TRANSACTION_PAYMENT_TYPES_READ: 'transaction-payment-types.read',
  TRANSACTION_PAYMENT_TYPES_CREATE: 'transaction-payment-types.create',
  TRANSACTION_PAYMENT_TYPES_UPDATE: 'transaction-payment-types.update',
  TRANSACTION_PAYMENT_TYPES_DELETE: 'transaction-payment-types.delete',
  // Resurs: transaction-categories
  TRANSACTION_CATEGORIES_READ: 'transaction-categories.read',
  TRANSACTION_CATEGORIES_CREATE: 'transaction-categories.create',
  TRANSACTION_CATEGORIES_UPDATE: 'transaction-categories.update',
  TRANSACTION_CATEGORIES_DELETE: 'transaction-categories.delete',
  // Resurs: transaction-change-requests
  TRANSACTION_CHANGE_REQUESTS_READ: 'transaction-change-requests.read',
  TRANSACTION_CHANGE_REQUESTS_CREATE: 'transaction-change-requests.create',
  TRANSACTION_CHANGE_REQUESTS_UPDATE: 'transaction-change-requests.update',
  TRANSACTION_CHANGE_REQUESTS_DELETE: 'transaction-change-requests.delete',
  // Resurs: documents
  DOCUMENTS_CREATE: 'documents.create',
  DOCUMENTS_UPDATE: 'documents.update',
  // Resurs: document-templates
  DOCUMENT_TEMPLATES_READ: 'document-templates.read',
  DOCUMENT_TEMPLATES_CREATE: 'document-templates.create',
  DOCUMENT_TEMPLATES_UPDATE: 'document-templates.update',
  // Resurs: document-sign-requests
  DOCUMENT_SIGN_REQUESTS_READ: 'document-sign-requests.read',
  DOCUMENT_SIGN_REQUESTS_CREATE: 'document-sign-requests.create',
  DOCUMENT_SIGN_REQUESTS_UPDATE: 'document-sign-requests.update',
  // Resurs: procurement-vendors
  PROCUREMENT_VENDORS_READ: 'procurement-vendors.read',
  PROCUREMENT_VENDORS_CREATE: 'procurement-vendors.create',
  PROCUREMENT_VENDORS_UPDATE: 'procurement-vendors.update',
  // Resurs: procurement-requests
  PROCUREMENT_REQUESTS_READ: 'procurement-requests.read',
  PROCUREMENT_REQUESTS_CREATE: 'procurement-requests.create',
  PROCUREMENT_REQUESTS_UPDATE: 'procurement-requests.update',
  // Resurs: procurement-orders
  PROCUREMENT_ORDERS_READ: 'procurement-orders.read',
  PROCUREMENT_ORDERS_CREATE: 'procurement-orders.create',
  PROCUREMENT_ORDERS_UPDATE: 'procurement-orders.update',
  // Resurs: procurement-receipts
  PROCUREMENT_RECEIPTS_READ: 'procurement-receipts.read',
  PROCUREMENT_RECEIPTS_CREATE: 'procurement-receipts.create',
  PROCUREMENT_RECEIPTS_UPDATE: 'procurement-receipts.update',
  // Resurs: assets-items
  ASSETS_ITEMS_READ: 'assets-items.read',
  ASSETS_ITEMS_CREATE: 'assets-items.create',
  ASSETS_ITEMS_UPDATE: 'assets-items.update',
  // Resurs: assets-maintenance
  ASSETS_MAINTENANCE_READ: 'assets-maintenance.read',
  ASSETS_MAINTENANCE_CREATE: 'assets-maintenance.create',
  ASSETS_MAINTENANCE_UPDATE: 'assets-maintenance.update',
  // Resurs: assets-depreciations
  ASSETS_DEPRECIATIONS_READ: 'assets-depreciations.read',
  ASSETS_DEPRECIATIONS_CREATE: 'assets-depreciations.create',
  ASSETS_DEPRECIATIONS_UPDATE: 'assets-depreciations.update',
  // Resurs: advanced-finance-invoices
  ADVANCED_FINANCE_INVOICES_READ: 'advanced-finance-invoices.read',
  ADVANCED_FINANCE_INVOICES_CREATE: 'advanced-finance-invoices.create',
  ADVANCED_FINANCE_INVOICES_UPDATE: 'advanced-finance-invoices.update',
  // Resurs: advanced-finance-scholarships
  ADVANCED_FINANCE_SCHOLARSHIPS_READ: 'advanced-finance-scholarships.read',
  ADVANCED_FINANCE_SCHOLARSHIPS_CREATE: 'advanced-finance-scholarships.create',
  ADVANCED_FINANCE_SCHOLARSHIPS_UPDATE: 'advanced-finance-scholarships.update',
  // Resurs: advanced-finance-refunds
  ADVANCED_FINANCE_REFUNDS_READ: 'advanced-finance-refunds.read',
  ADVANCED_FINANCE_REFUNDS_CREATE: 'advanced-finance-refunds.create',
  ADVANCED_FINANCE_REFUNDS_UPDATE: 'advanced-finance-refunds.update',
  // Resurs: advanced-finance-cashboxes
  ADVANCED_FINANCE_CASHBOXES_READ: 'advanced-finance-cashboxes.read',
  ADVANCED_FINANCE_CASHBOXES_CREATE: 'advanced-finance-cashboxes.create',
  ADVANCED_FINANCE_CASHBOXES_UPDATE: 'advanced-finance-cashboxes.update',
  // Resurs: advanced-finance-bank-transactions
  ADVANCED_FINANCE_BANK_TRANSACTIONS_READ: 'advanced-finance-bank-transactions.read',
  ADVANCED_FINANCE_BANK_TRANSACTIONS_CREATE: 'advanced-finance-bank-transactions.create',
  ADVANCED_FINANCE_BANK_TRANSACTIONS_UPDATE: 'advanced-finance-bank-transactions.update',
  // Resurs: transport-vehicles
  TRANSPORT_VEHICLES_READ: 'transport-vehicles.read',
  TRANSPORT_VEHICLES_CREATE: 'transport-vehicles.create',
  TRANSPORT_VEHICLES_UPDATE: 'transport-vehicles.update',
  // Resurs: transport-routes
  TRANSPORT_ROUTES_READ: 'transport-routes.read',
  TRANSPORT_ROUTES_CREATE: 'transport-routes.create',
  TRANSPORT_ROUTES_UPDATE: 'transport-routes.update',
  // Resurs: transport-stops
  TRANSPORT_STOPS_READ: 'transport-stops.read',
  TRANSPORT_STOPS_CREATE: 'transport-stops.create',
  TRANSPORT_STOPS_UPDATE: 'transport-stops.update',
  // Resurs: transport-assignments
  TRANSPORT_ASSIGNMENTS_READ: 'transport-assignments.read',
  TRANSPORT_ASSIGNMENTS_CREATE: 'transport-assignments.create',
  // Resurs: transport-trips
  TRANSPORT_TRIPS_READ: 'transport-trips.read',
  TRANSPORT_TRIPS_CREATE: 'transport-trips.create',
  TRANSPORT_TRIPS_UPDATE: 'transport-trips.update',
  // Resurs: health-safety-records
  HEALTH_SAFETY_RECORDS_READ: 'health-safety-records.read',
  HEALTH_SAFETY_RECORDS_CREATE: 'health-safety-records.create',
  HEALTH_SAFETY_RECORDS_UPDATE: 'health-safety-records.update',
  // Resurs: health-safety-nurse-visits
  HEALTH_SAFETY_NURSE_VISITS_READ: 'health-safety-nurse-visits.read',
  HEALTH_SAFETY_NURSE_VISITS_CREATE: 'health-safety-nurse-visits.create',
  HEALTH_SAFETY_NURSE_VISITS_UPDATE: 'health-safety-nurse-visits.update',
  // Resurs: health-safety-incidents
  HEALTH_SAFETY_INCIDENTS_READ: 'health-safety-incidents.read',
  HEALTH_SAFETY_INCIDENTS_CREATE: 'health-safety-incidents.create',
  HEALTH_SAFETY_INCIDENTS_UPDATE: 'health-safety-incidents.update',
  // Resurs: health-safety-drills
  HEALTH_SAFETY_DRILLS_READ: 'health-safety-drills.read',
  HEALTH_SAFETY_DRILLS_CREATE: 'health-safety-drills.create',
  HEALTH_SAFETY_DRILLS_UPDATE: 'health-safety-drills.update',
  // Resurs: crm-leads
  CRM_LEADS_READ: 'crm-leads.read',
  CRM_LEADS_CREATE: 'crm-leads.create',
  CRM_LEADS_UPDATE: 'crm-leads.update',
  CRM_LEADS_DELETE: 'crm-leads.delete',
  // Resurs: crm-lead-comments
  CRM_LEAD_COMMENTS_READ: 'crm-lead-comments.read',
  CRM_LEAD_COMMENTS_CREATE: 'crm-lead-comments.create',
  CRM_LEAD_COMMENTS_UPDATE: 'crm-lead-comments.update',
  CRM_LEAD_COMMENTS_DELETE: 'crm-lead-comments.delete',
  // Resurs: crm-tags
  CRM_TAGS_READ: 'crm-tags.read',
  CRM_TAGS_CREATE: 'crm-tags.create',
  CRM_TAGS_UPDATE: 'crm-tags.update',
  CRM_TAGS_DELETE: 'crm-tags.delete',
  // Resurs: crm-sources
  CRM_SOURCES_READ: 'crm-sources.read',
  CRM_SOURCES_CREATE: 'crm-sources.create',
  CRM_SOURCES_UPDATE: 'crm-sources.update',
  CRM_SOURCES_DELETE: 'crm-sources.delete',
  // Resurs: crm-referrals
  CRM_REFERRALS_READ: 'crm-referrals.read',
  CRM_REFERRALS_CREATE: 'crm-referrals.create',
  CRM_REFERRALS_UPDATE: 'crm-referrals.update',
  CRM_REFERRALS_DELETE: 'crm-referrals.delete',
  // Resurs: admissions-pipelines
  ADMISSIONS_PIPELINES_READ: 'admissions-pipelines.read',
  ADMISSIONS_PIPELINES_CREATE: 'admissions-pipelines.create',
  ADMISSIONS_PIPELINES_UPDATE: 'admissions-pipelines.update',
  // Resurs: admissions-stages
  ADMISSIONS_STAGES_READ: 'admissions-stages.read',
  ADMISSIONS_STAGES_CREATE: 'admissions-stages.create',
  ADMISSIONS_STAGES_UPDATE: 'admissions-stages.update',
  // Resurs: admissions-applications
  ADMISSIONS_APPLICATIONS_READ: 'admissions-applications.read',
  ADMISSIONS_APPLICATIONS_CREATE: 'admissions-applications.create',
  ADMISSIONS_APPLICATIONS_UPDATE: 'admissions-applications.update',
  // Resurs: admissions-exams
  ADMISSIONS_EXAMS_READ: 'admissions-exams.read',
  ADMISSIONS_EXAMS_CREATE: 'admissions-exams.create',
  ADMISSIONS_EXAMS_UPDATE: 'admissions-exams.update',
  // Resurs: admissions-decisions
  ADMISSIONS_DECISIONS_READ: 'admissions-decisions.read',
  ADMISSIONS_DECISIONS_CREATE: 'admissions-decisions.create',
  ADMISSIONS_DECISIONS_UPDATE: 'admissions-decisions.update',
  // Resurs: library-books
  LIBRARY_BOOKS_READ: 'library-books.read',
  LIBRARY_BOOKS_CREATE: 'library-books.create',
  LIBRARY_BOOKS_UPDATE: 'library-books.update',
  // Resurs: library-copies
  LIBRARY_COPIES_READ: 'library-copies.read',
  LIBRARY_COPIES_CREATE: 'library-copies.create',
  LIBRARY_COPIES_UPDATE: 'library-copies.update',
  // Resurs: library-loans
  LIBRARY_LOANS_READ: 'library-loans.read',
  LIBRARY_LOANS_CREATE: 'library-loans.create',
  LIBRARY_LOANS_UPDATE: 'library-loans.update',
  // Resurs: library-reservations
  LIBRARY_RESERVATIONS_READ: 'library-reservations.read',
  LIBRARY_RESERVATIONS_CREATE: 'library-reservations.create',
  LIBRARY_RESERVATIONS_UPDATE: 'library-reservations.update',
  // Resurs: inventory-categories
  INVENTORY_CATEGORIES_READ: 'inventory-categories.read',
  INVENTORY_CATEGORIES_CREATE: 'inventory-categories.create',
  INVENTORY_CATEGORIES_UPDATE: 'inventory-categories.update',
  // Resurs: inventory-items
  INVENTORY_ITEMS_READ: 'inventory-items.read',
  INVENTORY_ITEMS_CREATE: 'inventory-items.create',
  INVENTORY_ITEMS_UPDATE: 'inventory-items.update',
  // Resurs: inventory-transactions
  INVENTORY_TRANSACTIONS_READ: 'inventory-transactions.read',
  INVENTORY_TRANSACTIONS_CREATE: 'inventory-transactions.create',
  SUPER_ADMIN: '*.*',
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  FILES_READ: 'files.read',
  FILES_UPLOAD: 'files.upload',
  ROLES_READ: 'roles.read',
  ROLES_MANAGE: 'roles.manage',
  APPEALS_READ: 'appeals.read',
  APPEALS_MANAGE: 'appeals.manage',
  INTEGRATIONS_READ: 'integrations.read',
  INTEGRATIONS_MANAGE: 'integrations.manage',
  CRM_READ: 'crm.read',
  CRM_MANAGE: 'crm.manage',
  STUDENTS_READ: 'students.read',
  STUDENTS_CREATE: 'students.create',
  STUDENTS_UPDATE: 'students.update',
  STUDENTS_DELETE: 'students.delete',
  STUDENTS_MANAGE: 'students.manage',
  // Sub-resurs: o'quvchi ↔ ota-ona bog'lanishi
  STUDENT_PARENTS_READ: 'student-parents.read',
  STUDENT_PARENTS_CREATE: 'student-parents.create',
  STUDENT_PARENTS_DELETE: 'student-parents.delete',
  // Sub-resurs: o'quvchi hujjatlari
  STUDENT_DOCUMENTS_READ: 'student-documents.read',
  STUDENT_DOCUMENTS_CREATE: 'student-documents.create',
  STUDENT_DOCUMENTS_DELETE: 'student-documents.delete',
  ACADEMIC_READ: 'academic.read',
  ACADEMIC_MANAGE: 'academic.manage',
  // Resurs: o'quv yillari
  ACADEMIC_YEARS_READ: 'academic-years.read',
  ACADEMIC_YEARS_CREATE: 'academic-years.create',
  ACADEMIC_YEARS_UPDATE: 'academic-years.update',
  ACADEMIC_YEARS_DELETE: 'academic-years.delete',
  // Resurs: choraklar
  ACADEMIC_QUARTERS_READ: 'academic-quarters.read',
  ACADEMIC_QUARTERS_CREATE: 'academic-quarters.create',
  ACADEMIC_QUARTERS_UPDATE: 'academic-quarters.update',
  ACADEMIC_QUARTERS_DELETE: 'academic-quarters.delete',
  // Resurs: dars davrlari (lesson periods)
  ACADEMIC_LESSON_PERIODS_READ: 'academic-lesson-periods.read',
  ACADEMIC_LESSON_PERIODS_CREATE: 'academic-lesson-periods.create',
  ACADEMIC_LESSON_PERIODS_UPDATE: 'academic-lesson-periods.update',
  ACADEMIC_LESSON_PERIODS_DELETE: 'academic-lesson-periods.delete',
  // Resurs: fanlar
  ACADEMIC_SUBJECTS_READ: 'academic-subjects.read',
  ACADEMIC_SUBJECTS_CREATE: 'academic-subjects.create',
  ACADEMIC_SUBJECTS_UPDATE: 'academic-subjects.update',
  ACADEMIC_SUBJECTS_DELETE: 'academic-subjects.delete',
  // Resurs: kurslar
  ACADEMIC_COURSES_READ: 'academic-courses.read',
  ACADEMIC_COURSES_CREATE: 'academic-courses.create',
  ACADEMIC_COURSES_UPDATE: 'academic-courses.update',
  ACADEMIC_COURSES_DELETE: 'academic-courses.delete',
  // Resurs: sinflar (guruhlar)
  ACADEMIC_CLASSES_READ: 'academic-classes.read',
  ACADEMIC_CLASSES_CREATE: 'academic-classes.create',
  ACADEMIC_CLASSES_UPDATE: 'academic-classes.update',
  ACADEMIC_CLASSES_DELETE: 'academic-classes.delete',
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_MANAGE: 'attendance.manage',
  // Resurs: o'quvchi davomati yozuvlari
  ATTENDANCE_RECORDS_READ: 'attendance-records.read',
  ATTENDANCE_RECORDS_CREATE: 'attendance-records.create',
  FINANCE_READ: 'finance.read',
  FINANCE_MANAGE: 'finance.manage',
  // Resurs: shartnomalar
  FINANCE_CONTRACTS_READ: 'finance-contracts.read',
  FINANCE_CONTRACTS_CREATE: 'finance-contracts.create',
  // Resurs: to'lovlar (shartnoma bo'yicha)
  FINANCE_PAYMENTS_CREATE: 'finance-payments.create',
  // Resurs: o'qituvchi dars stavkalari
  FINANCE_TEACHER_RATES_READ: 'finance-teacher-rates.read',
  FINANCE_TEACHER_RATES_UPDATE: 'finance-teacher-rates.update',
  // Resurs: o'qituvchi oyliklari
  FINANCE_SALARIES_READ: 'finance-salaries.read',
  FINANCE_SALARIES_UPDATE: 'finance-salaries.update',
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_MANAGE: 'notifications.manage',
  SETTINGS_READ: 'settings.read',
  SETTINGS_MANAGE: 'settings.manage',
  HR_READ: 'hr.read',
  HR_MANAGE: 'hr.manage',
  // Resurs: hr-branches
  HR_BRANCHES_READ: 'hr-branches.read',
  HR_BRANCHES_CREATE: 'hr-branches.create',
  HR_BRANCHES_UPDATE: 'hr-branches.update',
  HR_BRANCHES_DELETE: 'hr-branches.delete',
  // Resurs: hr-departments
  HR_DEPARTMENTS_READ: 'hr-departments.read',
  HR_DEPARTMENTS_CREATE: 'hr-departments.create',
  HR_DEPARTMENTS_UPDATE: 'hr-departments.update',
  HR_DEPARTMENTS_DELETE: 'hr-departments.delete',
  // Resurs: hr-positions
  HR_POSITIONS_READ: 'hr-positions.read',
  HR_POSITIONS_CREATE: 'hr-positions.create',
  HR_POSITIONS_UPDATE: 'hr-positions.update',
  HR_POSITIONS_DELETE: 'hr-positions.delete',
  // Resurs: hr-staff
  HR_STAFF_READ: 'hr-staff.read',
  HR_STAFF_CREATE: 'hr-staff.create',
  HR_STAFF_UPDATE: 'hr-staff.update',
  HR_STAFF_DELETE: 'hr-staff.delete',
  // Resurs: hr-staff-certificates
  HR_STAFF_CERTIFICATES_READ: 'hr-staff-certificates.read',
  HR_STAFF_CERTIFICATES_CREATE: 'hr-staff-certificates.create',
  HR_STAFF_CERTIFICATES_UPDATE: 'hr-staff-certificates.update',
  HR_STAFF_CERTIFICATES_DELETE: 'hr-staff-certificates.delete',
  // Resurs: hr-staff-achievements
  HR_STAFF_ACHIEVEMENTS_READ: 'hr-staff-achievements.read',
  HR_STAFF_ACHIEVEMENTS_CREATE: 'hr-staff-achievements.create',
  HR_STAFF_ACHIEVEMENTS_UPDATE: 'hr-staff-achievements.update',
  HR_STAFF_ACHIEVEMENTS_DELETE: 'hr-staff-achievements.delete',
  // Resurs: hr-leaves
  HR_LEAVES_READ: 'hr-leaves.read',
  HR_LEAVES_CREATE: 'hr-leaves.create',
  HR_LEAVES_UPDATE: 'hr-leaves.update',
  HR_LEAVES_DELETE: 'hr-leaves.delete',
  // Resurs: hr-tasks
  HR_TASKS_READ: 'hr-tasks.read',
  HR_TASKS_CREATE: 'hr-tasks.create',
  HR_TASKS_UPDATE: 'hr-tasks.update',
  HR_TASKS_DELETE: 'hr-tasks.delete',
  // Resurs: hr-attendance
  HR_ATTENDANCE_READ: 'hr-attendance.read',
  HR_ATTENDANCE_CREATE: 'hr-attendance.create',
  HR_ATTENDANCE_UPDATE: 'hr-attendance.update',
  HR_ATTENDANCE_DELETE: 'hr-attendance.delete',
  // Resurs: hr-payrolls
  HR_PAYROLLS_READ: 'hr-payrolls.read',
  HR_PAYROLLS_CREATE: 'hr-payrolls.create',
  HR_PAYROLLS_UPDATE: 'hr-payrolls.update',
  // Resurs: hr-candidates
  HR_CANDIDATES_READ: 'hr-candidates.read',
  HR_CANDIDATES_CREATE: 'hr-candidates.create',
  HR_CANDIDATES_UPDATE: 'hr-candidates.update',
  HR_CANDIDATES_DELETE: 'hr-candidates.delete',
  // Resurs: hr-geofences
  HR_GEOFENCES_READ: 'hr-geofences.read',
  HR_GEOFENCES_CREATE: 'hr-geofences.create',
  HR_GEOFENCES_UPDATE: 'hr-geofences.update',
  HR_GEOFENCES_DELETE: 'hr-geofences.delete',
  // Resurs: hr-payments
  HR_PAYMENTS_READ: 'hr-payments.read',
  HR_PAYMENTS_CREATE: 'hr-payments.create',
  HR_PAYMENTS_UPDATE: 'hr-payments.update',
  HR_PAYMENTS_DELETE: 'hr-payments.delete',
  // Resurs: hr-interactions
  HR_INTERACTIONS_READ: 'hr-interactions.read',
  HR_INTERACTIONS_CREATE: 'hr-interactions.create',
  HR_INTERACTIONS_UPDATE: 'hr-interactions.update',
  HR_INTERACTIONS_DELETE: 'hr-interactions.delete',
  // Resurs: hr-performance-reviews
  HR_PERFORMANCE_REVIEWS_READ: 'hr-performance-reviews.read',
  HR_PERFORMANCE_REVIEWS_CREATE: 'hr-performance-reviews.create',
  HR_PERFORMANCE_REVIEWS_UPDATE: 'hr-performance-reviews.update',
  HR_PERFORMANCE_REVIEWS_DELETE: 'hr-performance-reviews.delete',
  // Resurs: hr-projects
  HR_PROJECTS_READ: 'hr-projects.read',
  HR_PROJECTS_CREATE: 'hr-projects.create',
  HR_PROJECTS_UPDATE: 'hr-projects.update',
  HR_PROJECTS_DELETE: 'hr-projects.delete',
  // Resurs: hr-surveys
  HR_SURVEYS_READ: 'hr-surveys.read',
  HR_SURVEYS_CREATE: 'hr-surveys.create',
  HR_SURVEYS_UPDATE: 'hr-surveys.update',
  HR_SURVEYS_DELETE: 'hr-surveys.delete',
  // Resurs: hr-teachers
  HR_TEACHERS_READ: 'hr-teachers.read',
  HR_TEACHERS_CREATE: 'hr-teachers.create',
  HR_TEACHERS_UPDATE: 'hr-teachers.update',
  HR_TEACHERS_DELETE: 'hr-teachers.delete',
  // Resurs: hr-timesheets
  HR_TIMESHEETS_READ: 'hr-timesheets.read',
  HR_TIMESHEETS_CREATE: 'hr-timesheets.create',
  HR_TIMESHEETS_UPDATE: 'hr-timesheets.update',
  HR_TIMESHEETS_DELETE: 'hr-timesheets.delete',
  // Resurs: hr-vacancies
  HR_VACANCIES_READ: 'hr-vacancies.read',
  HR_VACANCIES_CREATE: 'hr-vacancies.create',
  HR_VACANCIES_UPDATE: 'hr-vacancies.update',
  HR_VACANCIES_DELETE: 'hr-vacancies.delete',
  // Resurs: hr-work-schedules
  HR_WORK_SCHEDULES_READ: 'hr-work-schedules.read',
  HR_WORK_SCHEDULES_CREATE: 'hr-work-schedules.create',
  HR_WORK_SCHEDULES_UPDATE: 'hr-work-schedules.update',
  HR_WORK_SCHEDULES_DELETE: 'hr-work-schedules.delete',
  // Resurs: hr-statistics
  HR_STATISTICS_READ: 'hr-statistics.read',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_MANAGE: 'inventory.manage',
  YOUTH_READ: 'youth.read',
  YOUTH_MANAGE: 'youth.manage',
  LMS_READ: 'lms.read',
  LMS_MANAGE: 'lms.manage',
  // Resurs: baholar jurnali (gradebook)
  LMS_GRADEBOOK_READ: 'lms-gradebook.read',
  LMS_GRADEBOOK_UPDATE: 'lms-gradebook.update',
  // Resurs: dars jurnali (yozuvlar)
  LMS_JOURNAL_READ: 'lms-journal.read',
  LMS_JOURNAL_CREATE: 'lms-journal.create',
  LMS_JOURNAL_UPDATE: 'lms-journal.update',
  // Resurs: imtihon natijalari
  LMS_EXAM_RESULTS_READ: 'lms-exam-results.read',
  LMS_EXAM_RESULTS_CREATE: 'lms-exam-results.create',
  LMS_EXAM_RESULTS_UPDATE: 'lms-exam-results.update',
  // Resurs: imtihonlar
  LMS_EXAMS_READ: 'lms-exams.read',
  LMS_EXAMS_CREATE: 'lms-exams.create',
  LMS_EXAMS_UPDATE: 'lms-exams.update',
  LMS_EXAMS_DELETE: 'lms-exams.delete',
  // Resurs: dars jadvali (LMS lessons)
  LMS_LESSONS_READ: 'lms-lessons.read',
  LMS_LESSONS_CREATE: 'lms-lessons.create',
  LMS_LESSONS_UPDATE: 'lms-lessons.update',
  LMS_LESSONS_DELETE: 'lms-lessons.delete',
  ANALYTICS_READ: 'analytics.read',
  GAMIFICATION_READ: 'gamification.read',
  GAMIFICATION_MANAGE: 'gamification.manage',
  // Resurs: nishonlar (badge) + berish
  GAMIFICATION_BADGES_READ: 'gamification-badges.read',
  GAMIFICATION_BADGES_CREATE: 'gamification-badges.create',
  GAMIFICATION_BADGES_UPDATE: 'gamification-badges.update',
  // Resurs: o'quvchi hamyoni (coin balans)
  GAMIFICATION_WALLETS_READ: 'gamification-wallets.read',
  // Resurs: coin tranzaksiyalari
  GAMIFICATION_COINS_READ: 'gamification-coins.read',
  GAMIFICATION_COINS_CREATE: 'gamification-coins.create',
  // Resurs: coin shablonlari (preset)
  GAMIFICATION_COIN_PRESETS_READ: 'gamification-coin-presets.read',
  GAMIFICATION_COIN_PRESETS_CREATE: 'gamification-coin-presets.create',
  GAMIFICATION_COIN_PRESETS_UPDATE: 'gamification-coin-presets.update',
  GAMIFICATION_COIN_PRESETS_DELETE: 'gamification-coin-presets.delete',
  FEEDBACK_READ: 'feedback.read',
  FEEDBACK_MANAGE: 'feedback.manage',
  KPI_READ: 'kpi.read',
  KPI_MANAGE: 'kpi.manage',
  REPORTS_READ: 'reports.read',
  MOBILE_PORTAL_READ: 'mobile-portal.read',
  DOCUMENTS_READ: 'documents.read',
  DOCUMENTS_MANAGE: 'documents.manage',
  COMMUNICATION_READ: 'communication.read',
  COMMUNICATION_MANAGE: 'communication.manage',
  TRANSPORT_READ: 'transport.read',
  TRANSPORT_MANAGE: 'transport.manage',
  ACCESS_CONTROL_READ: 'access-control.read',
  ACCESS_CONTROL_MANAGE: 'access-control.manage',
  DATA_JOBS_READ: 'data-jobs.read',
  DATA_JOBS_MANAGE: 'data-jobs.manage',
  WORKFLOW_READ: 'workflow.read',
  WORKFLOW_MANAGE: 'workflow.manage',
  ADMISSIONS_READ: 'admissions.read',
  ADMISSIONS_MANAGE: 'admissions.manage',
  TIMETABLE_READ: 'timetable.read',
  TIMETABLE_MANAGE: 'timetable.manage',
  // Resurs: jadval shablonlari
  TIMETABLE_TEMPLATES_READ: 'timetable-templates.read',
  TIMETABLE_TEMPLATES_CREATE: 'timetable-templates.create',
  TIMETABLE_TEMPLATES_UPDATE: 'timetable-templates.update',
  // Resurs: jadval kataklari (slot)
  TIMETABLE_SLOTS_READ: 'timetable-slots.read',
  TIMETABLE_SLOTS_CREATE: 'timetable-slots.create',
  TIMETABLE_SLOTS_UPDATE: 'timetable-slots.update',
  // Resurs: almashtirishlar (substitution)
  TIMETABLE_SUBSTITUTIONS_READ: 'timetable-substitutions.read',
  TIMETABLE_SUBSTITUTIONS_CREATE: 'timetable-substitutions.create',
  TIMETABLE_SUBSTITUTIONS_UPDATE: 'timetable-substitutions.update',
  // Resurs: ziddiyatlar (conflict)
  TIMETABLE_CONFLICTS_READ: 'timetable-conflicts.read',
  TIMETABLE_CONFLICTS_CREATE: 'timetable-conflicts.create',
  TIMETABLE_CONFLICTS_UPDATE: 'timetable-conflicts.update',
  // Resurs: uy vazifalari (homework — LMS umbrella)
  HOMEWORK_ASSIGNMENTS_READ: 'homework-assignments.read',
  HOMEWORK_ASSIGNMENTS_CREATE: 'homework-assignments.create',
  HOMEWORK_ASSIGNMENTS_UPDATE: 'homework-assignments.update',
  HOMEWORK_SUBMISSIONS_READ: 'homework-submissions.read',
  HOMEWORK_SUBMISSIONS_CREATE: 'homework-submissions.create',
  HOMEWORK_SUBMISSIONS_UPDATE: 'homework-submissions.update',
  LIBRARY_READ: 'library.read',
  LIBRARY_MANAGE: 'library.manage',
  HEALTH_SAFETY_READ: 'health-safety.read',
  HEALTH_SAFETY_MANAGE: 'health-safety.manage',
  PROCUREMENT_READ: 'procurement.read',
  PROCUREMENT_MANAGE: 'procurement.manage',
  ASSETS_READ: 'assets.read',
  ASSETS_MANAGE: 'assets.manage',
  ADVANCED_FINANCE_READ: 'advanced-finance.read',
  ADVANCED_FINANCE_MANAGE: 'advanced-finance.manage',
  COUNSELING_READ: 'counseling.read',
  COUNSELING_MANAGE: 'counseling.manage',
} as const;

export type AppPermissionValue = (typeof AppPermission)[keyof typeof AppPermission];

export const DEFAULT_PERMISSION_CODES = Object.values(AppPermission);

/**
 * Confidential permissions that must NOT be folded into the broad
 * director/admin role grants. They protect data (e.g. encrypted psychologist
 * notes) that even top-level administrators are not allowed to read; only the
 * dedicated role — and the technical super-admin wildcard — may hold them.
 */
export const CONFIDENTIAL_PERMISSION_CODES: readonly string[] = [
  AppPermission.COUNSELING_READ,
  AppPermission.COUNSELING_MANAGE,
];

/**
 * Granular-ga bosqichma-bosqich o'tish xaritasi. Eski keng `<module>.manage`
 * kodi yangi `<resurs>.<amal>` yozuv kodlariga yoyiladi; eski `<module>.read`
 * yangi sub-resurs `read` kodlariga. Migratsiya (foydalanuvchi yaratgan
 * rollar) va seed (tizim rollari) IKKALASI ham shundan foydalanadi — bitta
 * manba, mos qoladi. Yangi modul granular qilinganda shu yerga qo'shiladi.
 */
export const MANAGE_EXPANSION: Record<string, string[]> = {
  [AppPermission.NOTIFICATIONS_MANAGE]: [
    AppPermission.NOTIFICATION_TEMPLATES_CREATE,
    AppPermission.NOTIFICATION_QUEUE_CREATE,
  ],
  [AppPermission.APPEALS_MANAGE]: [
    AppPermission.APPEALS_CREATE,
    AppPermission.APPEALS_UPDATE,
    AppPermission.APPEALS_DELETE,
    AppPermission.APPEALS_PUBLIC_LINK_CREATE,
  ],
  [AppPermission.INTEGRATIONS_MANAGE]: [
    AppPermission.INTEGRATIONS_CREATE,
    AppPermission.INTEGRATIONS_UPDATE,
    AppPermission.INTEGRATIONS_DELETE,
  ],
  [AppPermission.SETTINGS_MANAGE]: [
    AppPermission.SETTINGS_SCHOOL_UPDATE,
    AppPermission.SETTINGS_ROOMS_CREATE,
    AppPermission.SETTINGS_ROOMS_UPDATE,
    AppPermission.SETTINGS_ROOMS_DELETE,
  ],
  [AppPermission.ROLES_MANAGE]: [
    AppPermission.ROLES_CREATE,
    AppPermission.ROLES_UPDATE,
    AppPermission.ROLES_DELETE,
  ],
  [AppPermission.DATA_JOBS_MANAGE]: [
    AppPermission.DATA_JOBS_CREATE,
    AppPermission.DATA_JOBS_UPDATE,
  ],
  [AppPermission.COMMUNICATION_MANAGE]: [
    AppPermission.COMMUNICATION_TEMPLATES_CREATE,
    AppPermission.COMMUNICATION_TEMPLATES_UPDATE,
    AppPermission.COMMUNICATION_CAMPAIGNS_CREATE,
    AppPermission.COMMUNICATION_CAMPAIGNS_UPDATE,
    AppPermission.COMMUNICATION_DELIVERIES_CREATE,
    AppPermission.COMMUNICATION_DELIVERIES_UPDATE,
  ],
  [AppPermission.FEEDBACK_MANAGE]: [
    AppPermission.FEEDBACK_TICKETS_CREATE,
    AppPermission.FEEDBACK_TICKETS_UPDATE,
    AppPermission.FEEDBACK_COMMENTS_CREATE,
  ],
  [AppPermission.YOUTH_MANAGE]: [
    AppPermission.YOUTH_MEAL_MENUS_CREATE,
    AppPermission.YOUTH_MEAL_MENUS_UPDATE,
    AppPermission.YOUTH_REQUESTS_CREATE,
    AppPermission.YOUTH_REQUESTS_UPDATE,
  ],
  [AppPermission.KPI_MANAGE]: [
    AppPermission.KPI_METRICS_CREATE,
    AppPermission.KPI_METRICS_UPDATE,
    AppPermission.KPI_RESULTS_CREATE,
    AppPermission.KPI_RESULTS_UPDATE,
  ],
  [AppPermission.WORKFLOW_MANAGE]: [
    AppPermission.WORKFLOW_APPROVALS_CREATE,
    AppPermission.WORKFLOW_APPROVALS_UPDATE,
  ],
  [AppPermission.ACCESS_CONTROL_MANAGE]: [
    AppPermission.ACCESS_CONTROL_DEVICES_CREATE,
    AppPermission.ACCESS_CONTROL_DEVICES_UPDATE,
    AppPermission.ACCESS_CONTROL_FACE_PROFILES_CREATE,
    AppPermission.ACCESS_CONTROL_EVENTS_CREATE,
  ],
  [AppPermission.PROCUREMENT_MANAGE]: [
    AppPermission.PROCUREMENT_VENDORS_CREATE,
    AppPermission.PROCUREMENT_VENDORS_UPDATE,
    AppPermission.PROCUREMENT_REQUESTS_CREATE,
    AppPermission.PROCUREMENT_REQUESTS_UPDATE,
    AppPermission.PROCUREMENT_ORDERS_CREATE,
    AppPermission.PROCUREMENT_ORDERS_UPDATE,
    AppPermission.PROCUREMENT_RECEIPTS_CREATE,
    AppPermission.PROCUREMENT_RECEIPTS_UPDATE,
  ],
  [AppPermission.ASSETS_MANAGE]: [
    AppPermission.ASSETS_ITEMS_CREATE,
    AppPermission.ASSETS_ITEMS_UPDATE,
    AppPermission.ASSETS_MAINTENANCE_CREATE,
    AppPermission.ASSETS_MAINTENANCE_UPDATE,
    AppPermission.ASSETS_DEPRECIATIONS_CREATE,
    AppPermission.ASSETS_DEPRECIATIONS_UPDATE,
  ],
  [AppPermission.ADVANCED_FINANCE_MANAGE]: [
    AppPermission.ADVANCED_FINANCE_INVOICES_CREATE,
    AppPermission.ADVANCED_FINANCE_INVOICES_UPDATE,
    AppPermission.ADVANCED_FINANCE_SCHOLARSHIPS_CREATE,
    AppPermission.ADVANCED_FINANCE_SCHOLARSHIPS_UPDATE,
    AppPermission.ADVANCED_FINANCE_REFUNDS_CREATE,
    AppPermission.ADVANCED_FINANCE_REFUNDS_UPDATE,
    AppPermission.ADVANCED_FINANCE_CASHBOXES_CREATE,
    AppPermission.ADVANCED_FINANCE_CASHBOXES_UPDATE,
    AppPermission.ADVANCED_FINANCE_BANK_TRANSACTIONS_CREATE,
    AppPermission.ADVANCED_FINANCE_BANK_TRANSACTIONS_UPDATE,
  ],
  [AppPermission.TRANSPORT_MANAGE]: [
    AppPermission.TRANSPORT_VEHICLES_CREATE,
    AppPermission.TRANSPORT_VEHICLES_UPDATE,
    AppPermission.TRANSPORT_ROUTES_CREATE,
    AppPermission.TRANSPORT_ROUTES_UPDATE,
    AppPermission.TRANSPORT_STOPS_CREATE,
    AppPermission.TRANSPORT_STOPS_UPDATE,
    AppPermission.TRANSPORT_ASSIGNMENTS_CREATE,
    AppPermission.TRANSPORT_TRIPS_CREATE,
    AppPermission.TRANSPORT_TRIPS_UPDATE,
  ],
  [AppPermission.HEALTH_SAFETY_MANAGE]: [
    AppPermission.HEALTH_SAFETY_RECORDS_CREATE,
    AppPermission.HEALTH_SAFETY_RECORDS_UPDATE,
    AppPermission.HEALTH_SAFETY_NURSE_VISITS_CREATE,
    AppPermission.HEALTH_SAFETY_NURSE_VISITS_UPDATE,
    AppPermission.HEALTH_SAFETY_INCIDENTS_CREATE,
    AppPermission.HEALTH_SAFETY_INCIDENTS_UPDATE,
    AppPermission.HEALTH_SAFETY_DRILLS_CREATE,
    AppPermission.HEALTH_SAFETY_DRILLS_UPDATE,
  ],
  [AppPermission.CRM_MANAGE]: [
    AppPermission.CRM_LEADS_CREATE,
    AppPermission.CRM_LEADS_UPDATE,
    AppPermission.CRM_LEADS_DELETE,
    AppPermission.CRM_LEAD_COMMENTS_CREATE,
    AppPermission.CRM_LEAD_COMMENTS_UPDATE,
    AppPermission.CRM_LEAD_COMMENTS_DELETE,
    AppPermission.CRM_TAGS_CREATE,
    AppPermission.CRM_TAGS_UPDATE,
    AppPermission.CRM_TAGS_DELETE,
    AppPermission.CRM_SOURCES_CREATE,
    AppPermission.CRM_SOURCES_UPDATE,
    AppPermission.CRM_SOURCES_DELETE,
    AppPermission.CRM_REFERRALS_CREATE,
    AppPermission.CRM_REFERRALS_UPDATE,
    AppPermission.CRM_REFERRALS_DELETE,
  ],
  [AppPermission.ADMISSIONS_MANAGE]: [
    AppPermission.ADMISSIONS_PIPELINES_CREATE,
    AppPermission.ADMISSIONS_PIPELINES_UPDATE,
    AppPermission.ADMISSIONS_STAGES_CREATE,
    AppPermission.ADMISSIONS_STAGES_UPDATE,
    AppPermission.ADMISSIONS_APPLICATIONS_CREATE,
    AppPermission.ADMISSIONS_APPLICATIONS_UPDATE,
    AppPermission.ADMISSIONS_EXAMS_CREATE,
    AppPermission.ADMISSIONS_EXAMS_UPDATE,
    AppPermission.ADMISSIONS_DECISIONS_CREATE,
    AppPermission.ADMISSIONS_DECISIONS_UPDATE,
  ],
  [AppPermission.LIBRARY_MANAGE]: [
    AppPermission.LIBRARY_BOOKS_CREATE,
    AppPermission.LIBRARY_BOOKS_UPDATE,
    AppPermission.LIBRARY_COPIES_CREATE,
    AppPermission.LIBRARY_COPIES_UPDATE,
    AppPermission.LIBRARY_LOANS_CREATE,
    AppPermission.LIBRARY_LOANS_UPDATE,
    AppPermission.LIBRARY_RESERVATIONS_CREATE,
    AppPermission.LIBRARY_RESERVATIONS_UPDATE,
  ],
  [AppPermission.INVENTORY_MANAGE]: [
    AppPermission.INVENTORY_CATEGORIES_CREATE,
    AppPermission.INVENTORY_CATEGORIES_UPDATE,
    AppPermission.INVENTORY_ITEMS_CREATE,
    AppPermission.INVENTORY_ITEMS_UPDATE,
    AppPermission.INVENTORY_TRANSACTIONS_CREATE,
  ],
  [AppPermission.STUDENTS_MANAGE]: [
    AppPermission.STUDENTS_CREATE,
    AppPermission.STUDENTS_UPDATE,
    AppPermission.STUDENTS_DELETE,
    AppPermission.STUDENT_PARENTS_CREATE,
    AppPermission.STUDENT_PARENTS_DELETE,
    AppPermission.STUDENT_DOCUMENTS_CREATE,
    AppPermission.STUDENT_DOCUMENTS_DELETE,
    AppPermission.PARENT_COMMUNICATIONS_CREATE,
    AppPermission.PARENT_COMMUNICATIONS_UPDATE,
    AppPermission.PARENT_COMMUNICATIONS_DELETE,
  ],
  [AppPermission.ACADEMIC_MANAGE]: [
    AppPermission.ACADEMIC_YEARS_CREATE,
    AppPermission.ACADEMIC_YEARS_UPDATE,
    AppPermission.ACADEMIC_YEARS_DELETE,
    AppPermission.ACADEMIC_QUARTERS_CREATE,
    AppPermission.ACADEMIC_QUARTERS_UPDATE,
    AppPermission.ACADEMIC_QUARTERS_DELETE,
    AppPermission.ACADEMIC_LESSON_PERIODS_CREATE,
    AppPermission.ACADEMIC_LESSON_PERIODS_UPDATE,
    AppPermission.ACADEMIC_LESSON_PERIODS_DELETE,
    AppPermission.ACADEMIC_SUBJECTS_CREATE,
    AppPermission.ACADEMIC_SUBJECTS_UPDATE,
    AppPermission.ACADEMIC_SUBJECTS_DELETE,
    AppPermission.ACADEMIC_COURSES_CREATE,
    AppPermission.ACADEMIC_COURSES_UPDATE,
    AppPermission.ACADEMIC_COURSES_DELETE,
    AppPermission.ACADEMIC_CLASSES_CREATE,
    AppPermission.ACADEMIC_CLASSES_UPDATE,
    AppPermission.ACADEMIC_CLASSES_DELETE,
  ],
  [AppPermission.LMS_MANAGE]: [
    AppPermission.LMS_GRADEBOOK_UPDATE,
    AppPermission.LMS_JOURNAL_CREATE,
    AppPermission.LMS_JOURNAL_UPDATE,
    AppPermission.LMS_EXAM_RESULTS_CREATE,
    AppPermission.LMS_EXAM_RESULTS_UPDATE,
    AppPermission.LMS_EXAMS_CREATE,
    AppPermission.LMS_EXAMS_UPDATE,
    AppPermission.LMS_EXAMS_DELETE,
    AppPermission.LMS_LESSONS_CREATE,
    AppPermission.LMS_LESSONS_UPDATE,
    AppPermission.LMS_LESSONS_DELETE,
    // uy vazifalari LMS umbrella ostida
    AppPermission.HOMEWORK_ASSIGNMENTS_CREATE,
    AppPermission.HOMEWORK_ASSIGNMENTS_UPDATE,
    AppPermission.HOMEWORK_SUBMISSIONS_CREATE,
    AppPermission.HOMEWORK_SUBMISSIONS_UPDATE,
    AppPermission.GRADE_REQUESTS_CREATE,
    AppPermission.GRADE_REQUESTS_UPDATE,
    AppPermission.GRADE_REQUESTS_DELETE,
  ],
  [AppPermission.GAMIFICATION_MANAGE]: [
    AppPermission.GAMIFICATION_BADGES_CREATE,
    AppPermission.GAMIFICATION_BADGES_UPDATE,
    AppPermission.GAMIFICATION_COINS_CREATE,
    AppPermission.GAMIFICATION_COIN_PRESETS_CREATE,
    AppPermission.GAMIFICATION_COIN_PRESETS_UPDATE,
    AppPermission.GAMIFICATION_COIN_PRESETS_DELETE,
  ],
  [AppPermission.FINANCE_MANAGE]: [
    AppPermission.FINANCE_CONTRACTS_CREATE,
    AppPermission.FINANCE_PAYMENTS_CREATE,
    AppPermission.FINANCE_TEACHER_RATES_UPDATE,
    AppPermission.FINANCE_SALARIES_UPDATE,
    // tranzaksiyalar finance umbrella ostida
    AppPermission.TRANSACTIONS_CREATE,
    AppPermission.TRANSACTIONS_UPDATE,
    AppPermission.TRANSACTIONS_DELETE,
    AppPermission.TRANSACTION_PAYMENT_TYPES_CREATE,
    AppPermission.TRANSACTION_PAYMENT_TYPES_UPDATE,
    AppPermission.TRANSACTION_PAYMENT_TYPES_DELETE,
    AppPermission.TRANSACTION_CATEGORIES_CREATE,
    AppPermission.TRANSACTION_CATEGORIES_UPDATE,
    AppPermission.TRANSACTION_CATEGORIES_DELETE,
    AppPermission.TRANSACTION_CHANGE_REQUESTS_CREATE,
    AppPermission.TRANSACTION_CHANGE_REQUESTS_UPDATE,
    AppPermission.TRANSACTION_CHANGE_REQUESTS_DELETE,
  ],
  [AppPermission.DOCUMENTS_MANAGE]: [
    AppPermission.DOCUMENTS_CREATE,
    AppPermission.DOCUMENTS_UPDATE,
    AppPermission.DOCUMENT_TEMPLATES_CREATE,
    AppPermission.DOCUMENT_TEMPLATES_UPDATE,
    AppPermission.DOCUMENT_SIGN_REQUESTS_CREATE,
    AppPermission.DOCUMENT_SIGN_REQUESTS_UPDATE,
  ],
  [AppPermission.ATTENDANCE_MANAGE]: [AppPermission.ATTENDANCE_RECORDS_CREATE],
  [AppPermission.TIMETABLE_MANAGE]: [
    AppPermission.TIMETABLE_TEMPLATES_CREATE,
    AppPermission.TIMETABLE_TEMPLATES_UPDATE,
    AppPermission.TIMETABLE_SLOTS_CREATE,
    AppPermission.TIMETABLE_SLOTS_UPDATE,
    AppPermission.TIMETABLE_SUBSTITUTIONS_CREATE,
    AppPermission.TIMETABLE_SUBSTITUTIONS_UPDATE,
    AppPermission.TIMETABLE_CONFLICTS_CREATE,
    AppPermission.TIMETABLE_CONFLICTS_UPDATE,
  ],
  [AppPermission.HR_MANAGE]: [
    AppPermission.HR_BRANCHES_CREATE,
    AppPermission.HR_BRANCHES_UPDATE,
    AppPermission.HR_BRANCHES_DELETE,
    AppPermission.HR_DEPARTMENTS_CREATE,
    AppPermission.HR_DEPARTMENTS_UPDATE,
    AppPermission.HR_DEPARTMENTS_DELETE,
    AppPermission.HR_POSITIONS_CREATE,
    AppPermission.HR_POSITIONS_UPDATE,
    AppPermission.HR_POSITIONS_DELETE,
    AppPermission.HR_STAFF_CREATE,
    AppPermission.HR_STAFF_UPDATE,
    AppPermission.HR_STAFF_DELETE,
    AppPermission.HR_STAFF_CERTIFICATES_CREATE,
    AppPermission.HR_STAFF_CERTIFICATES_UPDATE,
    AppPermission.HR_STAFF_CERTIFICATES_DELETE,
    AppPermission.HR_STAFF_ACHIEVEMENTS_CREATE,
    AppPermission.HR_STAFF_ACHIEVEMENTS_UPDATE,
    AppPermission.HR_STAFF_ACHIEVEMENTS_DELETE,
    AppPermission.HR_LEAVES_CREATE,
    AppPermission.HR_LEAVES_UPDATE,
    AppPermission.HR_LEAVES_DELETE,
    AppPermission.HR_TASKS_CREATE,
    AppPermission.HR_TASKS_UPDATE,
    AppPermission.HR_TASKS_DELETE,
    AppPermission.HR_ATTENDANCE_CREATE,
    AppPermission.HR_ATTENDANCE_UPDATE,
    AppPermission.HR_ATTENDANCE_DELETE,
    AppPermission.HR_PAYROLLS_CREATE,
    AppPermission.HR_PAYROLLS_UPDATE,
    AppPermission.HR_CANDIDATES_CREATE,
    AppPermission.HR_CANDIDATES_UPDATE,
    AppPermission.HR_CANDIDATES_DELETE,
    AppPermission.HR_GEOFENCES_CREATE,
    AppPermission.HR_GEOFENCES_UPDATE,
    AppPermission.HR_GEOFENCES_DELETE,
    AppPermission.HR_PAYMENTS_CREATE,
    AppPermission.HR_PAYMENTS_UPDATE,
    AppPermission.HR_PAYMENTS_DELETE,
    AppPermission.HR_INTERACTIONS_CREATE,
    AppPermission.HR_INTERACTIONS_UPDATE,
    AppPermission.HR_INTERACTIONS_DELETE,
    AppPermission.HR_PERFORMANCE_REVIEWS_CREATE,
    AppPermission.HR_PERFORMANCE_REVIEWS_UPDATE,
    AppPermission.HR_PERFORMANCE_REVIEWS_DELETE,
    AppPermission.HR_PROJECTS_CREATE,
    AppPermission.HR_PROJECTS_UPDATE,
    AppPermission.HR_PROJECTS_DELETE,
    AppPermission.HR_SURVEYS_CREATE,
    AppPermission.HR_SURVEYS_UPDATE,
    AppPermission.HR_SURVEYS_DELETE,
    AppPermission.HR_TEACHERS_CREATE,
    AppPermission.HR_TEACHERS_UPDATE,
    AppPermission.HR_TEACHERS_DELETE,
    AppPermission.HR_TIMESHEETS_CREATE,
    AppPermission.HR_TIMESHEETS_UPDATE,
    AppPermission.HR_TIMESHEETS_DELETE,
    AppPermission.HR_VACANCIES_CREATE,
    AppPermission.HR_VACANCIES_UPDATE,
    AppPermission.HR_VACANCIES_DELETE,
    AppPermission.HR_WORK_SCHEDULES_CREATE,
    AppPermission.HR_WORK_SCHEDULES_UPDATE,
    AppPermission.HR_WORK_SCHEDULES_DELETE,
  ],
};

export const READ_EXPANSION: Record<string, string[]> = {
  [AppPermission.NOTIFICATIONS_READ]: [
    AppPermission.NOTIFICATION_TEMPLATES_READ,
  ],
  [AppPermission.APPEALS_READ]: [
    AppPermission.APPEALS_READ,
    AppPermission.APPEALS_PUBLIC_LINK_READ,
  ],
  [AppPermission.INTEGRATIONS_READ]: [
    AppPermission.INTEGRATIONS_READ,
  ],
  [AppPermission.SETTINGS_READ]: [
    AppPermission.SETTINGS_SCHOOL_READ,
    AppPermission.SETTINGS_ROOMS_READ,
  ],
  [AppPermission.ROLES_READ]: [
    AppPermission.ROLES_READ,
  ],
  [AppPermission.DATA_JOBS_READ]: [
    AppPermission.DATA_JOBS_READ,
  ],
  [AppPermission.COMMUNICATION_READ]: [
    AppPermission.COMMUNICATION_TEMPLATES_READ,
    AppPermission.COMMUNICATION_CAMPAIGNS_READ,
    AppPermission.COMMUNICATION_DELIVERIES_READ,
  ],
  [AppPermission.FEEDBACK_READ]: [
    AppPermission.FEEDBACK_TICKETS_READ,
    AppPermission.FEEDBACK_COMMENTS_READ,
  ],
  [AppPermission.YOUTH_READ]: [
    AppPermission.YOUTH_MEAL_MENUS_READ,
    AppPermission.YOUTH_REQUESTS_READ,
  ],
  [AppPermission.KPI_READ]: [
    AppPermission.KPI_METRICS_READ,
    AppPermission.KPI_RESULTS_READ,
  ],
  [AppPermission.WORKFLOW_READ]: [
    AppPermission.WORKFLOW_APPROVALS_READ,
  ],
  [AppPermission.ACCESS_CONTROL_READ]: [
    AppPermission.ACCESS_CONTROL_DEVICES_READ,
    AppPermission.ACCESS_CONTROL_FACE_PROFILES_READ,
    AppPermission.ACCESS_CONTROL_EVENTS_READ,
  ],
  [AppPermission.PROCUREMENT_READ]: [
    AppPermission.PROCUREMENT_VENDORS_READ,
    AppPermission.PROCUREMENT_REQUESTS_READ,
    AppPermission.PROCUREMENT_ORDERS_READ,
    AppPermission.PROCUREMENT_RECEIPTS_READ,
  ],
  [AppPermission.ASSETS_READ]: [
    AppPermission.ASSETS_ITEMS_READ,
    AppPermission.ASSETS_MAINTENANCE_READ,
    AppPermission.ASSETS_DEPRECIATIONS_READ,
  ],
  [AppPermission.ADVANCED_FINANCE_READ]: [
    AppPermission.ADVANCED_FINANCE_INVOICES_READ,
    AppPermission.ADVANCED_FINANCE_SCHOLARSHIPS_READ,
    AppPermission.ADVANCED_FINANCE_REFUNDS_READ,
    AppPermission.ADVANCED_FINANCE_CASHBOXES_READ,
    AppPermission.ADVANCED_FINANCE_BANK_TRANSACTIONS_READ,
  ],
  [AppPermission.TRANSPORT_READ]: [
    AppPermission.TRANSPORT_VEHICLES_READ,
    AppPermission.TRANSPORT_ROUTES_READ,
    AppPermission.TRANSPORT_STOPS_READ,
    AppPermission.TRANSPORT_ASSIGNMENTS_READ,
    AppPermission.TRANSPORT_TRIPS_READ,
  ],
  [AppPermission.HEALTH_SAFETY_READ]: [
    AppPermission.HEALTH_SAFETY_RECORDS_READ,
    AppPermission.HEALTH_SAFETY_NURSE_VISITS_READ,
    AppPermission.HEALTH_SAFETY_INCIDENTS_READ,
    AppPermission.HEALTH_SAFETY_DRILLS_READ,
  ],
  [AppPermission.CRM_READ]: [
    AppPermission.CRM_LEADS_READ,
    AppPermission.CRM_LEAD_COMMENTS_READ,
    AppPermission.CRM_TAGS_READ,
    AppPermission.CRM_SOURCES_READ,
    AppPermission.CRM_REFERRALS_READ,
  ],
  [AppPermission.ADMISSIONS_READ]: [
    AppPermission.ADMISSIONS_PIPELINES_READ,
    AppPermission.ADMISSIONS_STAGES_READ,
    AppPermission.ADMISSIONS_APPLICATIONS_READ,
    AppPermission.ADMISSIONS_EXAMS_READ,
    AppPermission.ADMISSIONS_DECISIONS_READ,
  ],
  [AppPermission.LIBRARY_READ]: [
    AppPermission.LIBRARY_BOOKS_READ,
    AppPermission.LIBRARY_COPIES_READ,
    AppPermission.LIBRARY_LOANS_READ,
    AppPermission.LIBRARY_RESERVATIONS_READ,
  ],
  [AppPermission.INVENTORY_READ]: [
    AppPermission.INVENTORY_CATEGORIES_READ,
    AppPermission.INVENTORY_ITEMS_READ,
    AppPermission.INVENTORY_TRANSACTIONS_READ,
  ],
  [AppPermission.STUDENTS_READ]: [
    AppPermission.STUDENT_PARENTS_READ,
    AppPermission.STUDENT_DOCUMENTS_READ,
    AppPermission.PARENT_COMMUNICATIONS_READ,
  ],
  [AppPermission.ACADEMIC_READ]: [
    AppPermission.ACADEMIC_YEARS_READ,
    AppPermission.ACADEMIC_QUARTERS_READ,
    AppPermission.ACADEMIC_LESSON_PERIODS_READ,
    AppPermission.ACADEMIC_SUBJECTS_READ,
    AppPermission.ACADEMIC_COURSES_READ,
    AppPermission.ACADEMIC_CLASSES_READ,
  ],
  [AppPermission.LMS_READ]: [
    AppPermission.LMS_GRADEBOOK_READ,
    AppPermission.LMS_JOURNAL_READ,
    AppPermission.LMS_EXAM_RESULTS_READ,
    AppPermission.LMS_EXAMS_READ,
    AppPermission.LMS_LESSONS_READ,
    AppPermission.HOMEWORK_ASSIGNMENTS_READ,
    AppPermission.HOMEWORK_SUBMISSIONS_READ,
    AppPermission.GRADE_REQUESTS_READ,
  ],
  [AppPermission.GAMIFICATION_READ]: [
    AppPermission.GAMIFICATION_BADGES_READ,
    AppPermission.GAMIFICATION_WALLETS_READ,
    AppPermission.GAMIFICATION_COINS_READ,
    AppPermission.GAMIFICATION_COIN_PRESETS_READ,
  ],
  [AppPermission.FINANCE_READ]: [
    AppPermission.FINANCE_CONTRACTS_READ,
    AppPermission.FINANCE_TEACHER_RATES_READ,
    AppPermission.FINANCE_SALARIES_READ,
    AppPermission.TRANSACTIONS_READ,
    AppPermission.TRANSACTION_PAYMENT_TYPES_READ,
    AppPermission.TRANSACTION_CATEGORIES_READ,
    AppPermission.TRANSACTION_CHANGE_REQUESTS_READ,
  ],
  [AppPermission.DOCUMENTS_READ]: [
    AppPermission.DOCUMENT_TEMPLATES_READ,
    AppPermission.DOCUMENT_SIGN_REQUESTS_READ,
  ],
  [AppPermission.ATTENDANCE_READ]: [AppPermission.ATTENDANCE_RECORDS_READ],
  [AppPermission.TIMETABLE_READ]: [
    AppPermission.TIMETABLE_TEMPLATES_READ,
    AppPermission.TIMETABLE_SLOTS_READ,
    AppPermission.TIMETABLE_SUBSTITUTIONS_READ,
    AppPermission.TIMETABLE_CONFLICTS_READ,
  ],
  [AppPermission.HR_READ]: [
    AppPermission.HR_BRANCHES_READ,
    AppPermission.HR_DEPARTMENTS_READ,
    AppPermission.HR_POSITIONS_READ,
    AppPermission.HR_STAFF_READ,
    AppPermission.HR_STAFF_CERTIFICATES_READ,
    AppPermission.HR_STAFF_ACHIEVEMENTS_READ,
    AppPermission.HR_LEAVES_READ,
    AppPermission.HR_TASKS_READ,
    AppPermission.HR_ATTENDANCE_READ,
    AppPermission.HR_PAYROLLS_READ,
    AppPermission.HR_CANDIDATES_READ,
    AppPermission.HR_GEOFENCES_READ,
    AppPermission.HR_PAYMENTS_READ,
    AppPermission.HR_INTERACTIONS_READ,
    AppPermission.HR_PERFORMANCE_REVIEWS_READ,
    AppPermission.HR_PROJECTS_READ,
    AppPermission.HR_SURVEYS_READ,
    AppPermission.HR_TEACHERS_READ,
    AppPermission.HR_TIMESHEETS_READ,
    AppPermission.HR_VACANCIES_READ,
    AppPermission.HR_WORK_SCHEDULES_READ,
    AppPermission.HR_STATISTICS_READ,
  ],
};

/**
 * Bitta kodni o'zi + (agar keng kod bo'lsa) yoyilgan granular kodlarga
 * aylantiradi. Keng bo'lmagan kod uchun faqat o'zini qaytaradi.
 */
export function expandPermissionCode(code: string): string[] {
  return [code, ...(MANAGE_EXPANSION[code] ?? []), ...(READ_EXPANSION[code] ?? [])];
}

/** Kod ro'yxatini yoyadi va takrorlarni olib tashlaydi (rol grantlari uchun). */
export function expandPermissionCodes(codes: readonly string[]): string[] {
  return Array.from(new Set(codes.flatMap((code) => expandPermissionCode(code))));
}
