export const AppPermission = {
  SUPER_ADMIN: '*.*',
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  FILES_READ: 'files.read',
  FILES_UPLOAD: 'files.upload',
  ROLES_READ: 'roles.read',
  ROLES_MANAGE: 'roles.manage',
  APPEALS_READ: 'appeals.read',
  APPEALS_MANAGE: 'appeals.manage',
  INTEGRATIONS_READ: 'integrations.read',
  INTEGRATIONS_MANAGE: 'integrations.manage',
  CRM_READ: 'crm.read',
  CRM_MANAGE: 'crm.manage',
  STUDENTS_READ: 'students.read',
  STUDENTS_MANAGE: 'students.manage',
  ACADEMIC_READ: 'academic.read',
  ACADEMIC_MANAGE: 'academic.manage',
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_MANAGE: 'attendance.manage',
  FINANCE_READ: 'finance.read',
  FINANCE_MANAGE: 'finance.manage',
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_MANAGE: 'notifications.manage',
  SETTINGS_READ: 'settings.read',
  SETTINGS_MANAGE: 'settings.manage',
  HR_READ: 'hr.read',
  HR_MANAGE: 'hr.manage',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_MANAGE: 'inventory.manage',
  YOUTH_READ: 'youth.read',
  YOUTH_MANAGE: 'youth.manage',
  LMS_READ: 'lms.read',
  LMS_MANAGE: 'lms.manage',
  ANALYTICS_READ: 'analytics.read',
  GAMIFICATION_READ: 'gamification.read',
  GAMIFICATION_MANAGE: 'gamification.manage',
  FEEDBACK_READ: 'feedback.read',
  FEEDBACK_MANAGE: 'feedback.manage',
  KPI_READ: 'kpi.read',
  KPI_MANAGE: 'kpi.manage',
  REPORTS_READ: 'reports.read',
  MOBILE_PORTAL_READ: 'mobile-portal.read',
  DOCUMENTS_READ: 'documents.read',
  DOCUMENTS_MANAGE: 'documents.manage',
  COMMUNICATION_READ: 'communication.read',
  COMMUNICATION_MANAGE: 'communication.manage',
  TRANSPORT_READ: 'transport.read',
  TRANSPORT_MANAGE: 'transport.manage',
  ACCESS_CONTROL_READ: 'access-control.read',
  ACCESS_CONTROL_MANAGE: 'access-control.manage',
  DATA_JOBS_READ: 'data-jobs.read',
  DATA_JOBS_MANAGE: 'data-jobs.manage',
  WORKFLOW_READ: 'workflow.read',
  WORKFLOW_MANAGE: 'workflow.manage',
  ADMISSIONS_READ: 'admissions.read',
  ADMISSIONS_MANAGE: 'admissions.manage',
  TIMETABLE_READ: 'timetable.read',
  TIMETABLE_MANAGE: 'timetable.manage',
  LIBRARY_READ: 'library.read',
  LIBRARY_MANAGE: 'library.manage',
  HEALTH_SAFETY_READ: 'health-safety.read',
  HEALTH_SAFETY_MANAGE: 'health-safety.manage',
  PROCUREMENT_READ: 'procurement.read',
  PROCUREMENT_MANAGE: 'procurement.manage',
  ASSETS_READ: 'assets.read',
  ASSETS_MANAGE: 'assets.manage',
  ADVANCED_FINANCE_READ: 'advanced-finance.read',
  ADVANCED_FINANCE_MANAGE: 'advanced-finance.manage',
  COUNSELING_READ: 'counseling.read',
  COUNSELING_MANAGE: 'counseling.manage',
} as const;

export type AppPermissionValue = (typeof AppPermission)[keyof typeof AppPermission];

export const DEFAULT_PERMISSION_CODES = Object.values(AppPermission);

/**
 * Confidential permissions that must NOT be folded into the broad
 * director/admin role grants. They protect data (e.g. encrypted psychologist
 * notes) that even top-level administrators are not allowed to read; only the
 * dedicated role — and the technical super-admin wildcard — may hold them.
 */
export const CONFIDENTIAL_PERMISSION_CODES: readonly string[] = [
  AppPermission.COUNSELING_READ,
  AppPermission.COUNSELING_MANAGE,
];
