import { ApiProperty, ApiPropertyOptional, PartialType } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsBoolean, IsEnum, IsISO8601, IsInt, IsNumber, IsOptional, IsString, IsUUID, Length, Max, Min } from 'class-validator';
import { RouteStatus, TripStatus, VehicleStatus } from '../enums/transport.enums';

export class CreateVehicleDto { @ApiProperty() @IsString() @Length(2, 40) plateNumber: string; @ApiProperty() @IsString() @Length(2, 120) model: string; @ApiProperty() @Type(() => Number) @IsInt() @Min(1) @Max(100) capacity: number; @ApiPropertyOptional({ format: 'uuid' }) @IsOptional() @IsUUID() driverId?: string; @ApiPropertyOptional({ enum: VehicleStatus }) @IsOptional() @IsEnum(VehicleStatus) status?: VehicleStatus; }
export class UpdateVehicleDto extends PartialType(CreateVehicleDto) {}
export class CreateRouteDto { @ApiProperty() @IsString() @Length(2, 160) name: string; @ApiPropertyOptional({ format: 'uuid' }) @IsOptional() @IsUUID() vehicleId?: string; @ApiPropertyOptional({ format: 'uuid' }) @IsOptional() @IsUUID() driverId?: string; @ApiPropertyOptional() @IsOptional() @IsString() startTime?: string; @ApiPropertyOptional() @IsOptional() @IsString() endTime?: string; @ApiPropertyOptional({ enum: RouteStatus }) @IsOptional() @IsEnum(RouteStatus) status?: RouteStatus; }
export class UpdateRouteDto extends PartialType(CreateRouteDto) {}
export class CreateRouteStopDto { @ApiProperty({ format: 'uuid' }) @IsUUID() routeId: string; @ApiProperty() @IsString() @Length(2, 180) name: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(0) orderIndex?: number; @ApiPropertyOptional() @IsOptional() @IsString() arrivalTime?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() latitude?: number; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() longitude?: number; }
export class UpdateRouteStopDto extends PartialType(CreateRouteStopDto) {}
export class AssignStudentTransportDto { @ApiProperty({ format: 'uuid' }) @IsUUID() studentId: string; @ApiProperty({ format: 'uuid' }) @IsUUID() routeId: string; @ApiPropertyOptional({ format: 'uuid' }) @IsOptional() @IsUUID() pickupStopId?: string; @ApiPropertyOptional({ format: 'uuid' }) @IsOptional() @IsUUID() dropoffStopId?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber({ maxDecimalPlaces: 2 }) @Min(0) monthlyFee?: number; @ApiPropertyOptional() @IsOptional() @IsBoolean() active?: boolean; }
export class CreateTransportTripDto { @ApiProperty({ format: 'uuid' }) @IsUUID() routeId: string; @ApiPropertyOptional({ format: 'uuid' }) @IsOptional() @IsUUID() vehicleId?: string; @ApiPropertyOptional({ format: 'uuid' }) @IsOptional() @IsUUID() driverId?: string; @ApiProperty() @IsISO8601() tripDate: string; @ApiPropertyOptional({ enum: TripStatus }) @IsOptional() @IsEnum(TripStatus) status?: TripStatus; }
export class UpdateTransportTripDto extends PartialType(CreateTransportTripDto) {}
